### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#10]
Add this based on psc-ide per atom package. Support from VSCode is there https://code.visualstudio.com/docs/extensionAPI/vscode-api#DefinitionProvider.

**Comment by texastoland** [comment]
Should I also add symbols view/navigation? Likewise for Atom.

**Comment by nwolverson** [comment]
Can do; for Atom there is a thing called symbols-view but only supports ctags (you can generate these with psc-docs but it isn't great). I guess it's just a filterable list of all document symbols though with goto-definition on selection? Rather than navigating based on a symbol in source you're looking at already.

**Comment by texastoland** [comment]
Yeah I suppose `DocumentSymbolProvider` is like a glossary compared to `DefinitionProvider`. It additionally provides visual context to differentiate between e.g. a `type` and `data` constructor of the same name. In theory it should also enable navigation by module name in addition to file from `Go to File…`.

**Comment by texastoland** [comment]
Regarding [renaming](https://code.visualstudio.com/docs/extensionAPI/vscode-api#RenameProvider) we'd need the positions of all references across the project CC @kRITZCREEK.

**Comment by nwolverson** [comment]
For renaming you really would want to operate on the AST (even for top level identifiers - need to be aware of shadowing). Similarly "find references" is useful but has the same issue, if it is to be any better than string search.

**Comment by texastoland** [comment]
You only need the AST for identifying them? A clash could simply be undone.

**Comment by nwolverson** [comment]
Fixed by 0e5286823b782e57ba5545a2d88449675524d48a

**Comment by texastoland** [comment]
WFM 💖

- Is it possible to link module that way?
- Neither args nor type params work but I assume that's because of `psc-ide`?

**Comment by nwolverson** [comment]
Should work for anything that you can get a tooltip for - top level defs only.

Module names is interesting - I suppose psc-ide already has this information but I don't think we can query it.  Not sure how useful this is. @kRITZCREEK any thoughts on file location lookup of modules?

**Comment by kRITZCREEK** [comment]
@nwolverson One thing that should be easy enough is to add the file location to the *list* command. I wouldn't want to mix module and type names again...

**Comment by texastoland** [comment]
> Not sure how useful this is.

From an end user perspective? It's perhaps not as useful as being able to go to a symbol. Currently I have to disable filtering `bower_components` and remember the filename (which isn't necessarily tied to its hierarchy). That would make the biggest impact on my workflow besides go to definition in general

> how does the editor figure out if it's looking at a module name or a type name.

The API expects the IDE service to know how to handle each thing. I suppose we could combine JSON from different API calls?

**Comment by nwolverson** [comment]
I think module names can only appear in imports anyway? Otherwise just as part of a qualified identifier. So for contextual stuff, I think that is enough - obviously could be an explicit 'go to module' command.

Not exactly hard to find module names correspondence with file names but may as well avoid parsing the files repeatedly - I think the list command suggestion sounds ideal.

**Comment by texastoland** [comment]
> I think module names can only appear in imports anyway?

True. Is the reasoning behind not including function arguments or type parameters locality? Might be useful for shadowing but we get warnings for that already.

> obviously could be an explicit 'go to module' command.

True but I'd rather see it in symbols. I suspect it could be used for autocompletion as well?

**Comment by nwolverson** [comment]
psc-ide only has any information for identifiers present in externs files, which generally means top level definitions which are exported (but non-exported tl definitions should present for the current file after rebuild).

"I'd rather see it in symbols" - I don't know what that means. Listed in "go to symbol" ?

Autocompletion - module names are autocompleted in imports in the Atom plugin

**Comment by texastoland** [comment]
> Listed in "go to symbol" ?

Affirmative.

> Autocompletion - module names are autocompleted in imports in the Atom plugin

Is there a ticket already here?

**Comment by nwolverson** [comment]
raised

#25 symbol provider
#26 module autocomplete
