### ISSUE TITLE
Re-exports being ignored

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#102]
On my windows machine with vscode-ide-purescript 0.17.0, purs 0.11.5, when completing something in Prelude I'm seeing the original import shown, not the preferred re-exported one:

![image](https://user-images.githubusercontent.com/2770891/36947245-3d535a0e-1fc1-11e8-866f-b2b35b35aeb3.png)

While the original module correctly appears on the tooltip it should appears as `Prelude (re-exported from ...)`, the completion inserts the wrong thing too. 

This is with the default 
```
"purescript.autocompleteGrouped": true,
"purescript.importsPreferredModules": [
      "Prelude"
],
"purescript.preludeModule": "Prelude"
```

Same 0.17.0 plugin version working fine on my mac.

**Comment by nwolverson** [comment]
Argh, the default setting requires purs `0.11.6` to work properly:

```
  // Whether to group completions in autocomplete results. Requires compiler 0.11.6
  "purescript.autocompleteGrouped": true
```

So if for some reason you're using 0.11.5, turn that off... I think on some older version it just won't have any impact if I recall correctly.

**Comment by natefaubion** [comment]
Is this not because you need 0.11.6? Or am I thinking of a different feature.
