### ISSUE TITLE
Imports only found after full build

### ISSUE THREAD

**Issue by joopringelberg** [nwolverson/vscode-ide-purescript#103]
**EXCUSE ME**: upon submitting I found I placed this issue in the wrong repository. I will recreate it in atom-ide-purescript.

Quick build of any file will result in errors for each import statement: "Module X was not found. Make sure the source file exists, and that it has been provided as an input to the compiler". After a full build, these errors disappear, only to reappear on a quick build of another file.

I have 

- purs 0.11.7
- pulp 12.0.1
- purescript-psa 0.6.0

installed globally and no local versions in node_modules. 
I run ide-purescript version 0.22 in Atom.
I use nvm (node version manager) and run the code under node version 6.5.0. All packages are installed from the same shell process using this node version.

The problem appeared first after upgrading purs (from 0.11.5 or 0.11.4). At the time, as I found out later, I had local versions of the dependencies installed, too.

**Comment by joopringelberg** [comment]
Solved my problem following a suggestion in atom-ide-purescript issue 167: delete output directory and rebuild. Sorry for the confusion.

**Comment by nwolverson** [comment]
This is certainly confusing. There should be a "quick fix" for those import errors that offers to do a rebuild in case this is the case. 

I'd like to make this better, with an explicit message that something's wrong: https://github.com/nwolverson/purescript-language-server/issues/18
