### ISSUE TITLE
Enabling debug output for `purescript.build`

### ISSUE THREAD

**Issue by ianbollinger** [nwolverson/vscode-ide-purescript#106]
So I goofed and forgot I had a per workspace configuration setting `purescript.buildCommand` that didn't work for a specific project folder I added to my workspace. So `purescript.build` wasn't working and I didn't know why. It would be nice if there were a way to trace what `purescript.build` is doing, or if there is, documentation for how to enable that debug output.

**Comment by nwolverson** [comment]
You should get some output on the "IDE PureScript" output pane (in particular at least the build command, and its completion, I think any stderr messages go there too)

**Comment by nwolverson** [comment]
Tried and don't see much there, just start and end of the command. Going to try and see if we can't get some more to appear.

**Comment by nwolverson** [comment]
This is done now. https://github.com/nwolverson/purescript-language-server/commit/f8daa4a1157ffe9a958266db8b67ff677ad6cdda
