### ISSUE TITLE
When change in js file is made, the file is not copied to output

### ISSUE THREAD

**Issue by safareli** [nwolverson/vscode-ide-purescript#108]
When change is made in purs file it's recompiled (and corresponding js file is copied to output).
When editing js file i expect same same to happen, i.e. copy edited js file to output and recompile corresponding purs file. now you need to go back to purs file and hit save there, which is not very productive.

What would be the best way to fix this issue?

**Comment by nwolverson** [comment]
Think this is something `purs ide` doesn't really cater for.

@kRITZCREEK thoughts? I could watch JS files and trigger a rebuild on the corresponding `.purs` (in the language server).

@safareli I recommend going back and editing the purs file, you shouldn't need to be spending long in the JS or there's something wrong ;)

**Comment by kRITZCREEK** [comment]
I don't really have a good answer here, other than what you've already said. Not sure if we could have something in the plugin that activates on a JS file only if there is a corresponding PS file.

**Comment by nwolverson** [comment]
I'll try this out and see how it works out.

**Comment by nwolverson** [comment]
This is implemented via https://github.com/nwolverson/purescript-language-server/pull/181 / #207
