### ISSUE TITLE
Fix typo reported to be broken

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#109]
From slack - fix typo is reported to give suggestion list and update the text, but not add import. Regular completion works to add import.

> For example: I write a code which needs an import. It is underscored with red. I click Ctrl+. and I get "Fix typo/add import". When I click on it I get a list of similar named functions but when i choose something, there is never an import added, only the function's name can get changed

**Comment by nwolverson** [comment]
I don't even see it suggested just now.

**Comment by i-am-the-slime** [comment]
I can only see it suggested when part of the typo is highlighted.

**Comment by nwolverson** [comment]
Fixed it not suggesting anything, but I need to apply the command twice to get the import

**Comment by nwolverson** [comment]
This is reworked and should be working now.
