### ISSUE TITLE
Add a way to explore all usage of some function/value

### ISSUE THREAD

**Issue by safareli** [nwolverson/vscode-ide-purescript#110]
Would be nice to be able to see where some particular function is used for example.

**Comment by nwolverson** [comment]
Find all references is supported with purs 0.12, for top level identifiers (same as everything else - due to `purs ide` support)

**Comment by nwolverson** [comment]
Closing as no reply & functionality exists in as much as it can - expansion to non top level identifiers is in the scope of `purs ide`.

(For reference shift+f12 invokes find all references by default - requires `purs ide` is passed source globs, see settings `purescript.sourcePath` and/or `purescript.addPscPackageSources` if this isn't lighting up for you on 0.12)
