### ISSUE TITLE
Not working on WSL

### ISSUE THREAD

**Issue by fabioluz** [nwolverson/vscode-ide-purescript#113]
Environment:
- node@8.11.3
- pulp@12.3.0
- purescript@0.12.0

Hi, 

This plugin is not working for me and I think that's because I'm missing some specific configuration for WSL. The VS Code is installed on Windows 10 but my Node environment (pulp + purescript) is running on Ubuntu 16.

Any idea about what I have to do make it work?

For example, to access the linux's terminal from VS Code I just have to point `  "terminal.integrated.shell.windows"` to `"C:\\WINDOWS\\Sysnative\\bash.exe"`. I believe I have to do something similar in the plugin's configuration.

Thank you!

**Comment by nwolverson** [comment]
I'd recommend not running on WSL :)

It's *probably* not something in this plugin but rather in https://github.com/nwolverson/purescript-language-server that would have to change - there's probably some sensitivity to paths being exactly the same - the LS uses both the files on disk and synced from the LSP, unfortunately.

I've never used WSL so I don't have a clue, presumably you have to do something to make sure the language server gets launched in WSL?

PRs welcome

**Comment by nwolverson** [comment]
For reference this issue may help https://github.com/alanz/vscode-hie-server/issues/99

**Comment by fabioluz** [comment]
I couldn't find a fix for this, so I decided to get back to Node on Windows. I hope the bugs are gone now.

**Comment by nwolverson** [comment]
With developments since this issue was raised, I think for WSL remote development (#123) should now be used, this has been tested with some of the other configs, though not WSL AFAIK. If somebody does have an issue with this extension with remote dev and WSL, I'd suggest a fresh issue at that point
