### ISSUE TITLE
Completion of Prim types may unnecessarily update imports

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#114]
Reported on slack: "I type Array but before finishing the word I press TAB. the extension adds an empty line at the top of the file, as if it would add an import"

`Array` is in `Prim`, I'm guessing this ran the add-imports stuff and the imports list is empty, resulting in some file reformatting.

**Comment by LucianU** [comment]
Indeed, the file in question doesn't have any imports. This happens with `String` as well. Probably it happens with all types that are in `Prim`.
