### ISSUE TITLE
Option to have new files created from a template

### ISSUE THREAD

**Issue by kevinbarabash** [nwolverson/vscode-ide-purescript#117]
The default template could be something like:
```
module Path.To.MyModule where

import Prelude

```
if the user creates a file called `MyModule.purs` in the directory `Path/To/`.

**Comment by nwolverson** [comment]
I wondered if this was a standard (extensible) vscode feature, but it looks not.

There's actually a generic extension for this: https://marketplace.visualstudio.com/items?itemName=bam.vscode-file-templates

Not sure if it's worth adding here or you can use that extension - I guess I'd be interested how many people would find this useful.

**Comment by i-am-the-slime** [comment]
This is this one, right: 
https://github.com/nwolverson/purescript-language-server/pull/169

Any chance of a release with this?

**Comment by nwolverson** [comment]
This is released for some time now.
