### ISSUE TITLE
The build error is uninformative (`Nothing` instead of port)

### ISSUE THREAD

**Issue by shamansir** [nwolverson/vscode-ide-purescript#121]
When I press Cmd+Shift+P and select _Purescript: Build_  in my project, I get the error: 

<img width="491" alt="Screenshot 2019-04-11 at 23 17 43" src="https://user-images.githubusercontent.com/110920/56082253-e1accb00-5e16-11e9-9e81-fc6199a769d7.png">

OS is: macOS 10.14.4 a.k.a Mojave
VSCode: 1.33.1
PureScript: 0.12.4
PureScript IDE extension: 0.20.8
PureScript Language Support Extension: 0.2.0

Through some debugging I found out that the reason are [these lines from `Build.purs`](https://github.com/nwolverson/purescript-language-server/blob/master/src/LanguageServer/IdePurescript/Build.purs#L115):

```purescript
    ServerState { port, conn, root }, _ -> do
      liftEffect $ logCb Error $ "Error running build: " <> show port <> " : " <> show root
      pure emptyDiagnostics
```

It's from Language Server plugin, but the issue itself I got in the IDE. All this could be connected to https://github.com/purescript/purescript/pull/3597, since on Mojave I get this error when I start `purs ide server`:

```
purs: Network.Socket.listen: unsupported operation (Operation not supported on socket)
```

**Comment by shamansir** [comment]
> It's from Language Server plugin, but the issue itself I got in the IDE. All this could be connected to purescript/purescript#3597, since on Mojave I get this error when I start `purs ide server`:

No, I've updated to v0.12.5, `purs ide server` is working now by itself, but the error is still there.

Build command is: `pulp build --json-errors`
PSC IDE Server: `purs ide server`

```
Pulp version 12.4.0
purs version 0.12.5 using /usr/local/bin/purs
```

macOS mojave

**Comment by shamansir** [comment]
I discovered the log and got my project running by removing:

```
rm -Rf ./bower_components/purescript-free/benchmark
rm -Rf ./bower_components/purescript-catenable-lists/benchmarks
```

Where files failed to be parsed by PureScript IDE:

```
[Info  - 3:21:10 PM] [Warn] Failed to parse: ["/Users/shamansir/Workspace/rpd-purs/bower_components/purescript-free/benchmark/Benchmark/Free0df59c5.purs","/Users/shamansir/Workspace/rpd-purs/bower_components/purescript-free/benchmark/Benchmark/Main.purs","/Users/shamansir/Workspace/rpd-purs/bower_components/purescript-catenable-lists/benchmarks/src/Benchmark.purs"]
```

Now everything works fine, and so this issue is only regarding uninformative error.

**Comment by nwolverson** [comment]
That error is indeed somewhat lacking, I don't know why I didn't at least tag the port and root parts that are being joined in! 

`[Warn] Failed to parse` will not have been causing anything to fail, I'm pretty sure as I have had two modules failing to parse for as long as I remember with everything working :)

**Comment by minkir014** [comment]
Does this project only breaks or all the others???

**Comment by shamansir** [comment]
Got this error several times again today, after the change to `spago`.

**Comment by nwolverson** [comment]
What change to spago? 

My understanding is that this error always means that, although you are attempting to run a build (which would maybe use `spago` depending on config), we are unable to start/connect to `purs ide server` for some reason - there should be some messages in the output pane complaining about this which may have more info.

I'd expect in this case nothing else (tooltips, completion etc) to work properly, and suggest
1. Ensure you have a PureScript "project" open as a workspace root folder
2. Remove any `.psc-ide-port` file lying around
3. Run the restart/reconnect IDE server command from the palette (Can't remember exact wording)

**Comment by d2ci8xc5** [comment]
Having the same problem described in the issue. Manually starting `purs ide server`/restarting via vscode nor removing outputs helps

**Comment by nwolverson** [comment]
@d2ci8xc5 the reason I always say "check the output pane" is that at the very start of output there, there should be a message saying what `purs` executable has been found, and the `PATH` being searched.

There is a history of issues caused by apps starting with different `PATH`s from launchers (particularly OSX dock) and command line, also in cases where multiple windows are joined from 1 root process.

**Comment by shamansir** [comment]
> What change to spago?

I've changed to `spago` and used `bower` before. I've got this error when I was using `spago v0.13`, but now `spago` is `v0.14` and I can't reproduce it, but still have other problems, for which I've created the #136.

**Comment by shamansir** [comment]
I still get this error again and again in different situations: while usually it builds OK, at some unpredictable point it just stops building and raises this error — and then it's stuck, no re-starting VSCode or restarting Purs IDE server helps.

Today it turned out I had a previous version of PureScript (0.12) which the extension was using, the 0.12 was at `/usr/local/bin/purs` and the proper one is `/opt/local/bin/purs`. While they are both in PATH and the shell prefers the proper one, the extension still tries `/usr/local/bin/purs`.

I've made a symlink to the proper version, but the build is still broken with no helpful information in the logs.

**Comment by nwolverson** [comment]
The message mentioned in the original issue here should now be fixed, the build will occur regardless of whether the IDE server is contactable, so the message is no longer required.

I can see there's some discussion of several issues here, some of which at least seem to be external issues (eg wrong PATH) - please open a specific issue with relevant title, info etc if there is an outstanding problem related to the extension.
