### ISSUE TITLE
remote development support?

### ISSUE THREAD

**Issue by safareli** [nwolverson/vscode-ide-purescript#123]
In case you missed VSCode just announced [remote development](https://code.visualstudio.com/blogs/2019/05/02/remote-development) support.

Not sure if there is need to make any code changes to support use of ide-pruescript for remote development, but there might be. 

Would be great if someone who tried/tries this, shares if everything works fine.

**Comment by nwolverson** [comment]
There's definitely an assumption that `purs ide` and other tools run directly in the filesystem of the workspace, eg in the containers model that should be running inside the development container, sounds like the concept covers this so should be possible ("Workspace Extensions", not sure how this jives with LSP)

**Comment by nwolverson** [comment]
I just tried this out with the "Remote - SSH" extension and it seems to work out fine. I opened a remote SSH workspace and opened a `.purs` file, the `language-purescript` extension was suggested for remote install, I clicked the "install on ssh: blah" button on the `ide-purescript` extension, and stuff just seems to work - getting `purs ide` based features and external commands running ok.

Closing for now but if anybody tries this with some other setup and runs into any issues, feel free to reopen or (preferably) make specific issues.
