### ISSUE TITLE
Completion on local variables

### ISSUE THREAD

**Issue by i-am-the-slime** [nwolverson/vscode-ide-purescript#125]
I find it quite unfortunate that it's not possible to complete on records like in other languages.

```purescript
myFun :: { field :: { nestedField :: Int } } -> _
myFun rec = rec.
```
Should suggest me to write `field`.

I can see this becoming quite difficult in general, e.g. nested uses of records.
However, I think it could be doable for top level arguments to functions that have been annotated like in the above example.
I assume this would be possible because I can hover over the types of the function arguments and see a tooltip with the type and count the arguments to functions.

What do you think?

**Comment by nwolverson** [comment]
We don't even have type tooltips or completion on top level arguments, never mind record fields.

> I assume this would be possible because I can hover over the types of the function arguments and see a tooltip with the type

This is not actually true, only the function itself will give you a tooltip. Hovering over the argument will give you nothing.

This is a reasonable desire but I think really depends on enhanced compiler support with AST based type information for starters. If and when such compiler work is done I'm sure that will make it into editor extensions.

**Comment by i-am-the-slime** [comment]
Sounds right, thank you!

**Comment by nwolverson** [comment]
I should mention that Christoph did some experimental work on record completion by abusing typed holes or some such, but I don't think it went any further
