### ISSUE TITLE
Importing /\ does not work

### ISSUE THREAD

**Issue by i-am-the-slime** [nwolverson/vscode-ide-purescript#127]
Explicitly works but it proposes to just import `/` instead of `/\`. When I then enter the missing `\` it imports it properly.

**Comment by nwolverson** [comment]
Can you be more explicit, what do you mean "importing /\". What actions are you performing, ie is this from a command invoked from the command palette, completion, what

**Comment by i-am-the-slime** [comment]
Yes, of course, sorry. By trying to reproduce this, I noticed that I was actually lying.

I cannot import the symbol `/\` from `Data.Tuple.Nested` with tab-completion, nor with "Add explicit import".

![importproblem](https://user-images.githubusercontent.com/1588055/65145595-371a8300-da1a-11e9-8396-37b732e5e539.gif)

**Comment by nwolverson** [comment]
Thanks, I'm not at all surprised that `/\` might be somehow awkward but the repro helps. 

The tab completion, looks like it's trying to complete for `\` because `/` is a separate token -ie the completion itself is not happening therefore there is no question of importing?

**Comment by i-am-the-slime** [comment]
Are you saying this is a limitation from VSCode and we can't do anything about it? Maybe file it upstream?

**Comment by nwolverson** [comment]
Need to look into it - it could be tokenisation on our side also
