### ISSUE TITLE
Outdated extension description on VS Code marketplace

### ISSUE THREAD

**Issue by uzantnomo** [nwolverson/vscode-ide-purescript#133]
[Extension description on marketplace](https://marketplace.visualstudio.com/items?itemName=nwolverson.ide-purescript) (which is also shown in VS Code extension page) is outdated and lacks info from the most recent [README.md](https://github.com/nwolverson/vscode-ide-purescript/blob/master/README.md), for example instruction on usage with spago.

**Comment by nwolverson** [comment]
This should finally be updated.
