### ISSUE TITLE
Tooltips for type info don't show up

### ISSUE THREAD

**Issue by amaurym** [nwolverson/vscode-ide-purescript#135]
>  Type info tooltips

I somehow don't see them in my vscode.

**Repro:**
- Install the plugin
- git clone https://github.com/JordanMartinez/learn-halogen
- npm install && npm build
- Open a .purs file
- Hover over a word

**Expected:**
Shows a tooltip.

**Actual:**
Nothing shows up.

**Notes:**
- The extension is loading up:
```
[2020-01-24 22:27:47.101] [exthost] [info] eager extensions activated
[2020-01-24 22:27:56.402] [exthost] [info] ExtensionService#_doActivateExtension nwolverson.ide-purescript {"startup":false,"extensionId":{"value":"nwolverson.ide-purescript","_lower":"nwolverson.ide-purescript"},"activationEvent":"onLanguage:purescript"}
[2020-01-24 22:27:56.402] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/amaurymartiny/.vscode/extensions/nwolverson.ide-purescript-0.20.8/out/src/extension
```
- This repo uses spago, may that be the reason?
- Do I need to have some binary in my PATH?

**Comment by nwolverson** [comment]
See the [README](https://github.com/nwolverson/vscode-ide-purescript#installation-and-general-use), you need `purs` available for the IDE server, either in your PATH or npm local bindir (if the corresponding setting is set).

Check the "IDE PureScript" output pane for debug info, this should show if `purs ide server` is able to be started and other relevant info.

**Comment by milesfrain** [comment]
I'm noticing a similar tooltip problem with the same [learn-halogen repo](https://github.com/JordanMartinez/learn-halogen).

Tooltips work great when first opening the project in vscode:
![image](https://user-images.githubusercontent.com/3578681/73786462-31fe6c00-474e-11ea-9c14-cea9572fbdae.png)

But once I save the file, tooltips stop displaying documentation:
![image](https://user-images.githubusercontent.com/3578681/73786592-7558da80-474e-11ea-9b06-6c692e9f2cd1.png)
This even occurs when saving after an edit that doesn't actually modify the file, such as adding a character then removing that same character.

Documentation for imported modules still works fine though:
![image](https://user-images.githubusercontent.com/3578681/73787062-573faa00-474f-11ea-81be-5d39466dba41.png)

If I restart vscode, then tooltip documentation for my local types is restored.

I suspected a rebuild-on-save might be causing these tooltip documentation issues, but rebuilding does not have any effect.
* Open vscode -> tooltips working -> rebuild -> tooltips still working
* Open vscode -> tooltips working -> save file -> tooltips broken -> rebuild -> tooltips still broken

Purescript 0.13.4
Purescript IDE 0.20.8

**Comment by milesfrain** [comment]
Some additional information:

Tooltips are restored by running `Stop/Disconnect purs IDE server` followed by `Restart/Reconnect purs IDE server`. Just running `Restart/Reconnect` by itself is not enough.

This might be related to #8, although imported modules also seem to have problems in that issue, rather than just local types.

**Comment by nwolverson** [comment]
@milesfrain looks like you have a completely different issue (you start by pointing out tooltips show up which is exactly the opposite of the issue), please don't add this to an existing issue. I've moved to a new issue.

@amaurymartiny did you manage to get this working? As you didn't respond again I assume either this now works or you stopped trying?

**Comment by nwolverson** [comment]
Closing the issue as it is old and no response was given
