### ISSUE TITLE
Add quick fix for missing type wrapper

### ISSUE THREAD

**Issue by kevinbarabash** [nwolverson/vscode-ide-purescript#137]
<img width="446" alt="Screen Shot 2020-02-29 at 8 37 09 PM" src="https://user-images.githubusercontent.com/1044413/75617918-88837e00-5b33-11ea-81a8-ba3d18ac4bb4.png">

It would be cool if there was a quick fix to transform` x / y` to `Maybe x / y`.

**Comment by nwolverson** [comment]
Hi, thanks for the report.

This would be a compiler issue (quick fixes are almost exclusively suggestions from the `purs` compiler). In this case I don't expect there's a nice general suggestion that would be accepted for the compiler. I'd say the focus would more be on ensuring the error messages convey the issue to the user most clearly
