### ISSUE TITLE
'ext:purs' does not find the plugin

### ISSUE THREAD

**Issue by mrakgr** [nwolverson/vscode-ide-purescript#138]
I had to to search for 'purescript' explicitly in the extensions marketplace.

**Comment by nwolverson** [comment]
That's odd, it does for me. Where are you searching "ext:purs" ? In the plugins pane?

**Comment by kritzcreek** [comment]
It's really weird. When you don't have any of the PS plugins installed and you click on the tooltip prompting you to install a plugin:
![image](https://user-images.githubusercontent.com/6189397/80303535-22248000-87b1-11ea-93ad-bcc52c30af82.png)
When you type the same query out by hand:
![image](https://user-images.githubusercontent.com/6189397/80303547-4718f300-87b1-11ea-9ef4-1f8dbcba8719.png)

**Comment by nwolverson** [comment]
Oh. Maybe it searches using more metadata once it has it cached or something. Though I notice purty "contributes" the purescript language, which I didn't previously think was the right thing to do - the language extension which provides the grammar does that, after all. Maybe that's what's appearing in the list when you click into that

**Comment by mrakgr** [comment]
@kritzcreek It was just like in your first screenshot. Right now I am trying it with an old Insiders version of VS Code that I still had installed and am getting that result. Strangely enough, just typing `purs` gives me the IDE, but not language support plugin.

With the newer version on which I had already installed the plugin, the marketplace search works properly.

**Comment by nwolverson** [comment]
![image](https://user-images.githubusercontent.com/2770891/88644105-75f97a80-d0ba-11ea-859d-15a78f0cdc61.png)

I added some keywords, this seems to show up on clicking the prompt now
