### ISSUE TITLE
Show an icon for .purs files

### ISSUE THREAD

**Issue by Kurren123** [nwolverson/vscode-ide-purescript#139]
Right now my editor looks like this:

![image](https://user-images.githubusercontent.com/3525980/79049253-68f37100-7c1a-11ea-8ab8-0d3becd2bde8.png)

I think it will look nice to show some proper icons for .purs files. I am happy to have a go at doing the PR for this if you'd like. I'd obviously confirm the icon first before submitting.

**Comment by nwolverson** [comment]
There's a PureScript icon included in the atom icons package: https://github.com/file-icons/atom
And for the icon itself, there should be a transparent png in the main purescript repo if I recall.

I didn't previously look into how icons are shown in vscode, it looks like https://github.com/vscode-icons/vscode-icons/ would be appropriate to contribute this to - the language (ID) provided by the `language-purescript` package is called `purescript`. Looking at the list of languages provided I think PureScript is hopefully popular enough to merit inclusion, they don't seem super restricted.

If you're able to contribute this that would be really cool :)

**Comment by Kurren123** [comment]
I see, it looks like it's up to the individual "theme" and "icon" extensions to add a purescript icon. That way the icon can perhaps be adjusted to better match the theme. Thank you for the direction, I'll look to contribute to the appropriate icon extensions.
