### ISSUE TITLE
 Command not found error in 0.20.14

### ISSUE THREAD

**Issue by thomashoneyman** [nwolverson/vscode-ide-purescript#141]
After auto-updating to vscode-ide-purescript v0.20.14, PureScript commands (`purescript.build`, `purescript.restartPscIde`, etc.) error with the message "command not found" in VSCode:

<img width="456" alt="Screen Shot 2020-04-25 at 11 46 28 AM" src="https://user-images.githubusercontent.com/10245104/80288174-05be1000-86eb-11ea-922d-c10c408641fd.png">

I am able to restore the commands by reverting to the previous release, PureScript IDE v0.20.8, but only if I also revert to vscode-language-purescript v0.2.1 (instead of v0.2.2, the latest). Also see https://github.com/nwolverson/vscode-language-purescript/issues/15 for the related ticket there.

**Comment by thomashoneyman** [comment]
I made a mistake switching versions; vscode-language-purescript works at v0.2.2, so the issue is only with vscode-ide-purescript.

**Comment by starper** [comment]
`PureScript: Start/Connect` command doesn't work either
```
Command 'PureScript: Start/Connect purs IDE server' resulted in an error (command 'purescript.startPscIde' not found)
```

**Comment by starper** [comment]
I'm not sure, but probably this is the source of this problem
```
Activating extension 'nwolverson.ide-purescript' failed: Cannot find module 'purescript-language-server'
```

**Comment by thomashoneyman** [comment]
Looks like that could be because of this change:

https://github.com/nwolverson/vscode-ide-purescript/commit/c327d34a1012f3ad02c149c0862bbc44679cb535#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L289

**Comment by milesfrain** [comment]
Rolling-back to a previous version (0.20.8) works for me.
[Roll-back instructions](https://github.com/Microsoft/vscode/issues/12764#issuecomment-442370545).
![image](https://user-images.githubusercontent.com/10746682/49140101-abe9c880-f2f3-11e8-80cb-96f4303e2a5e.gif)

**Comment by starper** [comment]
Those who use `Remote - Containers` can add something like this
```json
{
  ...
  "postCreateCommand": "cd ~/.vscode-server/extensions/nwolverson.ide-purescript-0.20.14 && npm install purescript-language-server@0.12.9",
  ...
}
```
to `devcontainer.json` as a temporary workaround

**Comment by nwolverson** [comment]
Sorry about this, seems like the language server dependency was dropped from the `package.json` just after I bumped it to the right version, for some reason. 0.20.15 is out which should fix this

**Comment by Lugoues** [comment]
@nwolverson I seem to still be getting this error on 0.20.15.  I tried both local and in a remote-container and both situations fail the same. Is there anything I can dig into to help debug this?

**Comment by nwolverson** [comment]
@Lugoues are you still experiencing this issue? Given it seemed to be resolved for others, you may not have the same issue, so any info you have would be useful

**Comment by nwolverson** [comment]
Closing this, seems like the issue was resolved
