### ISSUE TITLE
PureScript extension not always turns on

### ISSUE THREAD

**Issue by mjarosie** [nwolverson/vscode-ide-purescript#143]
Once in a while when I open a directory with PureScript project in it, the extension doesn't turn on. After `spago build`ing the project for the first time, when I invoke "PureScript: Restart/Reconnect purs IDE server" it results in the following error: `command 'purescript.restartPscIde' not found`.

![image](https://user-images.githubusercontent.com/9082353/81801039-b27df700-950b-11ea-9153-eb0525ef2db5.png)

Additionally the PureScript extension is not listed in the "outputs list" in the "OUTPUT" tab:

![image](https://user-images.githubusercontent.com/9082353/81801299-14d6f780-950c-11ea-91b8-c2d9ee79c7bd.png)

I'm not sure yet how to reproduce it consistently. Seems like the only resolution is to restart the vscode.

**Comment by nwolverson** [comment]
Did you actually open a `.purs` file? There should be certain triggers that start the extension, not sure if just opening a workspace is enough

**Comment by mjarosie** [comment]
Yes that was it. When I open a `.purs` file, everything works fine : )

Turning on the extension right after you open the workspace with a PureScript project would cause a better user experience I reckon. What do you think?

**Comment by nwolverson** [comment]
Going to add a trigger to start the extension in more situations without opening a `.purs` file, as it may be useful in some cases, but in most cases commands will still not do anything, as they are "text editor commands" and only operate in the context of a text editor - I don't think otherwise it is possible to support multi-root workspaces. Maybe with some contortions

**Comment by nwolverson** [comment]
Updated trigger in 0.21.2

**Comment by nwolverson** [comment]
The trigger has been in place for some time, I just made a change to also activate the language client on start - but only for workspaces with a single root folder. That means if you open a folder containing PureScript files matched by `src/**/*.purs`, the extension will activate even if there are no files open. In practice this doesn't allow you to do much, as all commands are editor commands requiring a PureScript file to be open - maybe that can be relaxed later.

For multi-root workspaces, I considered that it's better to trigger this lazily, one might not even be working on something in that PureScript project with the workspace open.
