### ISSUE TITLE
Make `spago` default

### ISSUE THREAD

**Issue by i-am-the-slime** [nwolverson/vscode-ide-purescript#144]
I think it's time to make spago the default.

**Comment by nwolverson** [comment]
The default what? 

[ ] Build command (`purescript.buildCommand` - currently `pulp`)
[ ] Enable adding sources (`purescript.addSpagoSources`)
[ ] Project discovery

I think it's already preferred for project discovery, and I agree on the other two. Did I miss anything?

There will probably be a big breaking release around the time of the next compiler release, so if not before then should definitely do it at that point.

**Comment by nwolverson** [comment]
Default now in 0.21.2
