### ISSUE TITLE
Error underlining doesn't update correctly

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#146]
I noticed this started happening with the latest vscode `1.46.0`.

![error-position](https://user-images.githubusercontent.com/144058/84930799-b2cb5e00-b086-11ea-816a-e6c0093faa44.gif)

**Comment by nwolverson** [comment]
Well that sounds like a vscode bug :(

**Comment by natefaubion** [comment]
Hmm... I didn’t notice it in other languages, only PS. Maybe they are running on every key press though.

**Comment by natefaubion** [comment]
FWIW found this old issue, but I don't know enough about the current implementation. https://github.com/Microsoft/vscode/issues/41299

**Comment by natefaubion** [comment]
https://github.com/microsoft/vscode/issues/90890#issuecomment-621306853 this ticket indicates that it is the responsibility of the extension to make sure squiggles track content changes.

**Comment by natefaubion** [comment]
https://github.com/microsoft/vscode/issues/102724#issuecomment-660262456 more current discussion.

**Comment by nwolverson** [comment]
Thanks, that looks to be exactly it. I always thought it was clever behaviour that VSCode did the right thing here, hopefully it can be restored somehow. 

Possibly constantly rebuilding will be enough to make this nice again, we should have that option anyway, otherwise we get into the unfortunate situation of pushing diagnostic positions around to track text edits

**Comment by natefaubion** [comment]
I'm not sure how that would work with `purs ide`, which still writes to `output`. I think it would be odd to write out externs for files that haven't been saved.

**Comment by nwolverson** [comment]
Good point, not sure where to go on that one - it's a feature requested some time ago https://github.com/nwolverson/purescript-language-server/issues/53 

Even using a temp file as the module source, I guess the output directory is the same. Maybe that's one to postpone for when the language server is integrated into `purs ide` ;)

**Comment by natefaubion** [comment]
I think purs-ide at the very least would just have to get an option to check a file, but not write out externs. It could potentially cache that result, and if it gets a subsequent request to check the file again (with not changes) but write externs, it can flush what it has. cc @kritzcreek

**Comment by natefaubion** [comment]
https://github.com/microsoft/vscode/issues/103953

**Comment by natefaubion** [comment]
Looks like this will be reverted in the August milestone.

**Comment by nwolverson** [comment]
@natefaubion thanks for tracking this one, I hope it's not bugging you too much :)

**Comment by nwolverson** [comment]
Now in September milestone, tagged as 'feature request'

**Comment by natefaubion** [comment]
Unfortunately, this is now backlogged.

**Comment by nwolverson** [comment]
At this point I may bother to have a crack at making the current behaviour less annoying. Given this is going to be a change in the language server it's probably worth trying to come up with some balance of irritation at too-few and too-wrong squiggles across a couple of editors (even though if the spec is unclear vscode is no doubt the defacto driver of what to do)

**Comment by nwolverson** [comment]
@natefaubion I just looked into those issues again, while the latest of the issues you linked is unresolved, I believe the commit that stopped squiggles moving around as you edit was reverted way back when: https://github.com/microsoft/vscode/commit/85304e386cad2ce51e1a2ae7fd58c0863309809a

And having tested (and indeed not noticed the issue in general usage), I think we're back to the original situation, squiggles will move down if you insert newlines before a warning, for example (but the problems view reports the original, now incorrect, line numbers). If you edit/delete the offending text then sure, you'll end up with a persistant empty squiggle, but not the behaviour you show above.

**Comment by natefaubion** [comment]
Ah yeah, this has been working for a while. Forgot to close this 😄
