### ISSUE TITLE
Reduce notifications

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#15]
In Atom I changed non-essential notifications to use a status bar icon instead, I think we also have an API for that here. Could think about this as well as reducing some.

**Comment by texastoland** [comment]
Haha I thought it quit working at first 😝 WFM!

**Comment by texastoland** [comment]
A single notification for an explicit build command would be helpful.

**Comment by nwolverson** [comment]
Even when it's successful? I thought the status bar indicates it's done..maybe the build takes too long for that to be reasonable?

**Comment by texastoland** [comment]
Only because the status bar is so subliminal. That's super helpful for fast rebuild but sometimes I wonder whether it happened or not. Previously each build caused 3 notifications.

**Comment by nwolverson** [comment]
fb0f20dac7fbec4a0dbbfb57b4f4357757c751a4

**Comment by texastoland** [comment]
🙌
