### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by milesfrain** [nwolverson/vscode-ide-purescript#153]
While poking around, I found some purs code that seems to be unused.

For example:
https://github.com/nwolverson/vscode-ide-purescript/blob/8dd53b3e6731209bee94a0304f66c1a9dbefdf8c/src/IdePurescript/VSCode/Config.purs#L39-L40

Is there an automated way to detect all of this?

**Comment by nwolverson** [comment]
Not that I'm aware of - given that the module has open exports, this is only unused in the context of an application entry point (ie it is probably removed by `purs bundle`).

(Within a given module, see https://github.com/purescript/purescript/pull/3819)
