### ISSUE TITLE
Add explicit import stopped working

### ISSUE THREAD

**Issue by i-am-the-slime** [nwolverson/vscode-ide-purescript#154]
This feature used to work really well and now nothing happens when I trigger it.

**Comment by kurtmilam** [comment]
I can confirm that this feature works up to v0.21.1 but no longer works in v0.21.2 or v0.21.3 for me.

The console doesn't report any errors when I try to use the feature.

**Comment by kurtmilam** [comment]
It seems like some other commands that worked (or at least did something) in `v0.21.1` stopped working as of `v0.21.2`. 'Case Split' is an example.

**Comment by nwolverson** [comment]
Appears to be an issue of some TypeScript bundling introduced in a recent version upgrade.
