### ISSUE TITLE
Tried to run addCase

### ISSUE THREAD

**Issue by cheery** [nwolverson/vscode-ide-purescript#155]
Hi @nwolverson, can you tell me what is the story with this feature? It is not in the list on the README, but there is a menu item for it. It's one of the superb features of Purescript, just like how it is that in Idris.

I was trying to use this `addCase` feature, but I don't figure how to make it work. It's listed in the Ctrl+Shift+P menu, when I move the cursor over and click the menu item, nothing happens. I'm trying this on Ubuntu linux.

If it is broken, I will help you fix it. You've already provided development guide on the readme, so I'll read that for starters and set it up so I can study this plugin. I've written a VSCode plugin before although it was years ago.

**Comment by nwolverson** [comment]
Thanks for the report. Per #154 looks like I managed to disable some commands with a recent release, I'll look into it

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by nwolverson** [comment]
Regarding documentation, the README could do with improvment (#156). There should be feature-parity with the atom plugin, for some reason case split is demo'd there but not here: https://github.com/nwolverson/atom-ide-purescript/

**Comment by cheery** [comment]
I promised to help you fix it, and I write all the time. I could update that.

Additionally I would suggest, lets add this:

> For all functions provided by the IDE server you will need to build your project first! This can either be via the built-in build command, or via an external tool - but if you do build externally, you should be sure to Restart/Reconnect purs IDE server (accessed through CTRL+SHIFT+P/CMD+SHIFT+P) afterwards, or the IDE server will not be able to pick up any changes. All the available functionality can be found from the menu, prefixed with "PureScript".

When I was reading this, and I haven't used VSCode for a long time, I was wondering where the commands went? This would have helped me to know where to look.

**Comment by nwolverson** [comment]
Feel free to PR README improvements - or comment on the linked issue as to what is missing. 

I don't understand "where the commands went"?

**Comment by cheery** [comment]
When you have installed, it is nice to see the list of the commands. In [psc-ide-vim] they have a line to check `:help psc-ide-vim`. I eventually ended up noticing this, but I did look where to access the commands a little while because I've only ever used VSCode to dogfood a plugin I wrote.
Specifically, like this:
![vscode-commands](https://user-images.githubusercontent.com/1215420/89893044-55fca780-dbe0-11ea-9762-72d9d9bc06a6.png)

**Comment by nwolverson** [comment]
OK. That sounds like partly an editor familiarity issue, but certainly the commands should be listed in the README - I feel like a section (perhaps headed by an image like that one) with a demo of each command would be great. I like the demo gifs like [atom add clause](https://github.com/nwolverson/atom-ide-purescript#case-split--add-clause) [psc-ide-emacs completion](https://github.com/purescript-emacs/psc-ide-emacs#get-completions-from-the-modules-you-imported-while-you-type-through-company-mode) at least for multi step features

**Comment by nwolverson** [comment]
Relevant to this actual issue the problem appears to be a TypeScript bundling issue I've introduced in a version upgrade

**Comment by cheery** [comment]
The gifs sound like a splendid idea. I get to read the atom ide readme for update.

**Comment by nwolverson** [comment]
Believe this was resolved in a release already.
