### ISSUE TITLE
Unexpectedly edits (changes format) of (other) imports while adding import

### ISSUE THREAD

**Issue by whitecolor** [nwolverson/vscode-ide-purescript#166]
I have following import format of Prelude (in a column) 
![image](https://user-images.githubusercontent.com/736697/102127779-bc375680-3e6e-11eb-9815-bc15b6cd2dde.png)

After I add `put` from `Avar` as displayed on screenshot. Format of Prelude import changes to be one line:

![image](https://user-images.githubusercontent.com/736697/102127742-b2155800-3e6e-11eb-8e92-ee9089fb364a.png)

I believe this is not expected and inappropriate behavior.

But I don't actually get who is doing this formatting and sorting? I have disabled purty.

Output of IDE PureScript:
```
[Info  - 12:38:34 AM] Adding import of put from (Just "Effect.AVar") with type filter (Just "NSValue")
(Just { textDocument: { codeAction: { codeActionLiteralSupport: { codeActionKind: { valueSet: [CodeActionKind ,CodeActionKind quickfix,CodeActionKind refactor,CodeActionKind refactor.extract,CodeActionKind refactor.inline,CodeActionKind refactor.rewrite,CodeActionKind source,CodeActionKind source.organizeImports] } }, isPreferredSupport: true } }, workspace: { applyEdit: true, workspaceEdit: { documentChanges: true } } })
Literals supported: (Just true)
Built with 9/9 issues for file: "d:\\Code\\psalm\\src\\Core\\Platform.purs", all diagnostic files: ["d:\\Code\\psalm\\src\\Core\\Platform.purs"]
(Just { textDocument: { codeAction: { codeActionLiteralSupport: { codeActionKind: { valueSet: [CodeActionKind ,CodeActionKind quickfix,CodeActionKind refactor,CodeActionKind refactor.extract,CodeActionKind refactor.inline,CodeActionKind refactor.rewrite,CodeActionKind source,CodeActionKind source.organizeImports] } }, isPreferredSupport: true } }, workspace: { applyEdit: true, workspaceEdit: { documentChanges: true } } })
Literals supported: (Just true)
```

UPD. actually, this happens on any property access from imported namespaces.

**Comment by nwolverson** [comment]
Sorry, this is working as intended, the PureScript compiler is used to update imports when you do tab-completion, and it formats in a standard format - it has to layout the edited code somehow, and does not attempt to follow your existing layout in any way. 

There are basically 2 options - care about the imports layout, and maintain them yourself, or delegate import management to the compiler (by which I mean, `purs ide server`). If you're editing the import list manually - and it looks like you are - you can turn off import management in the VSCode plugin:

![image](https://user-images.githubusercontent.com/2770891/102201499-1f040e80-3ebe-11eb-9821-059e9395015f.png)

The intended usage here is actually that you can complete anywhere in your file and imports will be managed for you - you don't need to edit the import list at all.

FYI, the standard style  is to leave `Prelude` as an "open import", ie just `import Prelude` with no `()` list and specify the imports only on everything else.

**Comment by whitecolor** [comment]
> it formats in a standard format - it has to layout the edited code somehow and does not attempt to follow your existing layout in any way


It is nice that things are done automatically, but who defines the "standard way"? -) I believe Purescript in general lacks a standardized view on the form of the code.

So the standard way currently:

- Flattens each statement into one line
- Sorts the imports
- Removes the comments if they were between imports
- Leaves single upper import separated by an empty line (Usually it is Prelude)

So probably potentially it could be "smarter"?
- Do not flatten each import statements into one line if the import was not flattened, but keep the formatting
- Keep comments and empty lines between the imports (if the user want to structure imports that way)
- Apply sorting not to all imports but to groups (separate by empty or comment line)

Well, this might be just an over-complication, so it is just an idea. What do think about it?

**Comment by nwolverson** [comment]
The PureScript compiler (specifically, `purs ide`) defines the standard way, as far as I am concernced - not least because it is the compiler which is doing this formatting - any change suggestion should be directed at the compiler repository. As far as this extension/the language server are concerned, the option would be to turn off auto imports, or influence the compiler behaviour.

(Of course you're welcome to format your own code as you like)

Note where you say "upper import", this section is specifically the (unqualified) open imports.

**Comment by whitecolor** [comment]
Ok, I get it, thanks.
