### ISSUE TITLE
Regression in `Add explicit import`

### ISSUE THREAD

**Issue by i-am-the-slime** [nwolverson/vscode-ide-purescript#170]
I used to be able to invoke: Add explicit import on a type and then it would get imported or in case of ambiguity I would get asked which one. Now I can only get imports to work with autocomplete.

---

I was able to pinpoint that this works with version `0.21.4` and is broken since `0.23.0`

It looks like the main change between versions was a bump of the language server from `0.13.7` to `0.14.0`. I'll investigate what happened there.

---

This is my current prime suspect:

https://github.com/nwolverson/purescript-language-server/commit/4facf79569fdebdd0f3e9770b4ad844bb19d7144

**Comment by i-am-the-slime** [comment]
I tried to debug this/find out what could be causing it but ultimately failed. However, I noticed in the process that there's `⌘+.` now which subsumes this behaviour for me.

**Comment by nwolverson** [comment]
I do believe this is now resolved with updates to imports/explicit imports, see discussion here https://github.com/nwolverson/purescript-language-server/pull/123
