### ISSUE TITLE
IDE complain Module not found after upgrading package set with spago

### ISSUE THREAD

**Issue by katsujukou** [nwolverson/vscode-ide-purescript#175]
## Problem
Recently I have updated purescript version to `0.14.1`.  
After upgrading package-set by running `spago upgrade-set`, PureScript IDE says all packages installed via `spago install` not found. 

## What I tried
 - remove `.spago` and `.output`, then fully re-build
 - `Restart/Recconect purs IDE server`
 - explicitly provide `purescript.packagePath` in settins.json 
 -  restart VS Code

However, none of these helped me.

**Comment by nwolverson** [comment]
Not sure about the reference to `.output`, you would normally mean `output` - maybe typo. 

"Module not found" normally means either the code is not built, or there is a version mismatch. Given you say you fully rebuilt, I suspect for some reason your build process and VS Code are hitting different `purs` versions. The VS Code extension/language server will find `purs` in your `PATH`, but that includes the `npm` local path if the corresponding option is set, which may differ from your "full build"

Check the "Output" pane, at the very top after the Language Server starts it will list out the `purs` binary being used, you can check it's the one you expect

**Comment by katsujukou** [comment]
After remove `output` and then building project, the VS Code extension found right version of `purs` and it worked.

My development environment is built with nix, and I tried several things including 
 - setting `purescript.pursExe` to the full path to the `purs` bin in the nix store
 - uninstalling globally installed purescript via `nix-env`
 - `nix-collect-gabage` 
but I think none of these were not necessary, just removing `output` was the right way.

**Comment by nwolverson** [comment]
Closing this, seems the issue was resolved
