### ISSUE TITLE
Automatic build doesn't use custom build command

### ISSUE THREAD

**Issue by texastoland** [nwolverson/vscode-ide-purescript#18]
I noticed because I see censored warnings but realized it's just fast rebuild. When it's disabled would it be reasonable to queue up a normal build?

**Comment by texastoland** [comment]
I noticed because I see censored warnings but realized it's fast rebuild. When it's disabled would it be reasonable to queue up a normal build?

**Comment by nwolverson** [comment]
Could be, that's what I do on the Atom package - but there the history was it used to always do a full build on save if enabled, whereas here I never added it before fast rebuild.

If there's demand we can certainly add a build on save option similarly (so 1. should we build on save and 2. should it use fast rebuild - defaulting both true).

**Comment by texastoland** [comment]
Sounds good to me. The underlying problem is different build behaviors. Naively we could incorporate psa as a library. But it sounds like the case for project level configuration. Do you have a compiler issue to chime in on?

**Comment by nwolverson** [comment]
I'm not entirely sure I follow, it sounds like you may be talking about several different issues.

*  I can see a case to running a full build on save, but it's slow and (depending on your build process) may not provide adequate tooling support 
*  I can also see benefits to adding support for censoring warnings on 'fast rebuild' (is there anything else?)

Fundamentally to my mind there are 2 separate things, one being providing support to give immediate feedback to you in the editor on errors (this is what psc-ide and rebuild in particular give you), and the other is to run a "proper" build process, produce your artefact etc.  But I appreciate it can be a bit more fuzzy...

**Comment by texastoland** [comment]
My use case is solely the latter. I ignore type declarations since I only care for exported API but the get highlighted between rebuilds anyway.

**Comment by nwolverson** [comment]
Going to close this, as on reflection I don't think running a full build on save is a good idea, and confuses the two concepts. With the error filtering issue above resolved, I don't see a reason to leave this open.
