### ISSUE TITLE
Publish extension on Open VSX registry

### ISSUE THREAD

**Issue by sigma-andex** [nwolverson/vscode-ide-purescript#183]
Would it be possible to publish this extension on the [Open VSX Registry](https://open-vsx.org/)?
Online code editing tools like [Gitpod.io](https://gitpod.io) use the open vsx registry, and not the Microsoft one, though I'm not sure which one Github code spaces or Theia use. 

Having it in the Open VSX registry allows to use Purescript at least on Gitpod and therefore develop Purescript with limited devices, like a tablet.  I have bundled it locally and tried it out by manually uploading & installing it and it works like a charm, so there shouldn't be any customisations necessary. 

The documentation on publishing on Open VSX can be found here https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
Seems pretty straight forward imho.
The same would be necessary for the vscode-language-purescript repository, I have created an [issue there as well](https://github.com/nwolverson/vscode-language-purescript/issues/23).

**Comment by kajetansw** [comment]
Hi, @sigma-andex, me and probably others would benefit from a possibility to share their projects using GitPod. People would have an access to a really quick setup for PureScript projects to run and play with. 

Is there a possibility to make this happen?

**Comment by nwolverson** [comment]
It appears that @emattiza has taken it upon themselves to publish this extension (and the language extension) to open-vsix. You could use that for now, however I do intend to set up publishing under the usual namespace as part of the extension release process, so that both registries will be synchronised in future.

**Comment by emattiza** [comment]
> It appears that @emattiza has taken it upon themselves to publish this extension (and the language extension) to open-vsix. You could use that for now, however I do intend to set up publishing under the usual namespace as part of the extension release process, so that both registries will be synchronised in future.

Happy to unpub and support you in anyway :) thank you for the extension!

**Comment by nwolverson** [comment]
@emattiza thanks, if you can leave that up for now at least until I manage to set up publishing, that would be great, I'll update on this issue.

**Comment by nwolverson** [comment]
This is now published to Open VSX, with much thanks to @emattiza for a PR with CI setup

https://open-vsx.org/extension/nwolverson/ide-purescript
