### ISSUE TITLE
Wrong purs path taken when using nvm

### ISSUE THREAD

**Issue by bklaric** [nwolverson/vscode-ide-purescript#196]
I'm using [nvm](https://github.com/nvm-sh/nvm) for development. I was working on a project using:
- node 10.10.0
- purs 0.13.8

I started a new project and decided to upgrade node and purs. Now I have:
- node 16.13.0
- purs 0.14.5

After `spago init` when I build the template project from console, everything works fine. However, building it through the extension (`PureScript: Build` command) fails because the extension somehow keeps using the previous purs 0.13.8.

Here's the relevant extension log:
```
[Info  - 17:58:04] Resolved IDE server paths (npm-bin: false) from PATH of /home/bklaric/.nvm/versions/node/v10.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin (1st is used):
[Info  - 17:58:04] /home/bklaric/.nvm/versions/node/v10.10.0/bin/purs: 0.13.8

[Info  - 17:58:04] Found existing port from file: 15139, cwd: /home/bklaric/github/crypto-trader
[Info  - 17:58:04] Found IDE server on port 15139 with correct path: /home/bklaric/github/crypto-trader
[Info  - 17:58:04] Found existing IDE server with correct path on port 15139
[Info  - 17:58:04] Error loading modules: Version mismatch for the externs at: /home/bklaric/github/crypto-trader/output/Data.Show.Generic/externs.cbor Expected: 0.13.8 Found: 0.14.5
```

PATH seems to be completely wrong since doing `echo $PATH` gives me:
```
/home/bklaric/.nvm/versions/node/v16.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

I've tried reopening VSCode, reinstalling the extension and disabling sync to no avail.

**Comment by nwolverson** [comment]
The PATH is the path that vscode gets, I have observed rarely before the wrong PATH been picked up with multiple vscode windows open. Try the following:

1. Close all vscode windows
2. Check for/kill any remaining processes
3. Launch code from the terminal after ensuring `PATH` is correct

**Comment by bklaric** [comment]
I restarted my laptop, did
```
$ echo $PATH
/home/bklaric/.nvm/versions/node/v16.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ code .
```
and now the extension picks up the correct path and purs bin. Looks like you were right, VSCode needs to be closed meticulously after changing PATH.

**Comment by nwolverson** [comment]
Closing as I believe the issue was resolved (and in any case is not originating in this extension).

Please feel free to reopen if that is not correct.
