### ISSUE TITLE
Pursuit search doesn't work

### ISSUE THREAD

**Issue by makeartandgames** [nwolverson/vscode-ide-purescript#198]
It just creates an empty input field; I fill this out, press enter to submit =>  I get another empty input field, which I am not able to submit or make go away except by hitting escape. 

 I get the same behavior with module and non-module search. 

PureScript IDE v0.25.6

VS Code info:

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by nwolverson** [comment]
Thanks, I can repro.
