### ISSUE TITLE
Suggestions remain after applying

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#20]
Weird stuff happens when you apply them multiple times...

Need to remove them after applying fix.

**Comment by sgronblo** [comment]
Maybe you could have been more specific so I could know if I ran into the same problem.

I have `import Data.Maybe` which shows a suggestion:
```
Module Data.Maybe has unspecified imports, consider using the explicit form:

    import Data.Maybe (Maybe(..))
```

But when I click the lightbulb I get this result `import Data.Maybe (Maybe(..))` and the suggestion can be clicked endlessly resulting in an additional `(Maybe(..))` added to the end of the line.

**Comment by nwolverson** [comment]
Yes, the same.

**Comment by nwolverson** [comment]
Don't think this is an issue now. The maybe example above now working fine for me without persisting suggestion
