### ISSUE TITLE
New option for syntax highlighting of MissingTypeDeclaration

### ISSUE THREAD

**Issue by taksuyu** [nwolverson/vscode-ide-purescript#206]
Is there any chance we can have a new option for the syntax highlighting of MissingTypeDeclaration? As it stands, highlighting the whole function, including the body, cause the function itself doesn't have a type is hard to read. I'd love to see an option to highlight only the function name.

I would be happy to write the PR if you can point me in the general direction of the code that has to be changed. 

Thanks for developing this plugin; it makes my life much easier!

**Comment by nwolverson** [comment]
I agree that the behaviour is not the most usable.

This is a PureScript compiler issue (and should be raised in https://github.com/purescript/purescript), the range is set in the warning generated by the compiler. You can see the same line/column range given by the compiler output - more obvious if you use `psa` to show you the source covered by the warning messages. 

(You can check the output of the compiler with `--json-errors` - that's exactly what's beign used by the language server to generate editor highlighting)
