### ISSUE TITLE
Is there a way to remove "export (export only this) | export everything else"

### ISSUE THREAD

**Issue by jstoxrocky** [nwolverson/vscode-ide-purescript#208]
Like this image shows. I find this annoying. Are there some settings or config I could tweak?

<img width="335" alt="Screen Shot 2022-09-05 at 7 37 38 PM" src="https://user-images.githubusercontent.com/5459666/188517966-facdb92e-3d67-4f0b-b5b0-147854fd0685.png">

**Comment by JordanMartinez** [comment]
Pretty sure that's the "Export Lenses" feature that can be disabled in the settings.

**Comment by nwolverson** [comment]
Yes, in vscode settings it is "Purescript: Exports Code Lens" and can be toggled off

**Comment by jstoxrocky** [comment]
Thanks all!
