### ISSUE TITLE
Build shortcut

### ISSUE THREAD

**Issue by texastoland** [nwolverson/vscode-ide-purescript#21]
I think this should work after nwolverson/vscode-language-purescript#1:

```json
{
  "key": "shift+cmd+b",
  "command": "purescript.build",
  "when": "editorTextFocus && editorLangId == 'purescript'"
}
```

**Comment by texastoland** [comment]
Not working for me but trying to find the SO post I saw a couple days ago.

**Comment by texastoland** [comment]
Had a type but otherwise works like a champ!

**Comment by nwolverson** [comment]
I have this in my local keybindings and it works already:

```
{ "key": "ctrl+shift+b", "command": "purescript.build", "when": "editorTextFocus && editorLangId == 'purescript'" }
```

Can add a keybinding to this extension but I'm not sure what code's approach to platform-relative keybindings are

**Comment by nwolverson** [comment]
Aha there are properties to set platform-specific overrides https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeskeybindings
