### ISSUE TITLE
Go to symbol in workspace does nothing in 0.26

### ISSUE THREAD

**Issue by Savelenko** [nwolverson/vscode-ide-purescript#210]
It seems that `Go to Symbol in Workspace... (Ctrl+T)` stopped working in `v0.26.0` Downgrading to `v0.25.12` brings the expected functionality back. My steps in detail are as follows:

* Create a new empty project with `purs 0.15.6` using `spago init`
* Open VS Code
* Hit `Ctrl+T` and search for `main` (project source) or `logShow` (installed library source).
* Nothing found
* Downgrade the extenstion to `v0.25.12` and reload the workspace
* Hit `Ctr+T` again and repeat the search
* Results found as expected
* Update the extension to `v0.26.0` again
* `Ctrl+T` stops working again

**Comment by nwolverson** [comment]
I can reproduce, in fact I happened to have an old window open where it works, and the new one it does not. Thanks for the report

**Comment by nwolverson** [comment]
What this auto closes because I said fixed in another repo...fun.


Latest version should have this change https://github.com/nwolverson/vscode-ide-purescript/releases/tag/v0.26.1

**Comment by Savelenko** [comment]
Thank you!
