### ISSUE TITLE
Support go-to symbol

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#25]
I think this requires effectively psc-ide `complete` command to return source information. (or a *lot* of calls)

https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentSymbolProvider
https://code.visualstudio.com/docs/extensionAPI/vscode-api#WorkspaceSymbolProvider

@kRITZCREEK is there a reason this is provided just for `type` query - is it expensive to query? Looks to me like it's there but discarded

**Comment by kRITZCREEK** [comment]
Not really. It's there but I didn't want to make the completion results too big, since I was worried our "one-line" delimiting might break down. Also tried to keep breaking changes as small as possible. Should we look at adding that next?

**Comment by nwolverson** [comment]
A lot is on the order of 'once for each identifier that completion over all modules would return'. VS Code has a "search symbol across entire workspace" command which requires that the full position metadata is returned when the list is displayed. Possibly could get around this by limiting the result set to 10-20 and requiring further filtering. 

Options I could imagine are: allowing a list of identifiers for `type` (so I would do this as 2 calls in this case, and `type` is a kind of "full info" command); or if worried about the overhead in adding this to all `complete` calls (which I agree is useless most of the time) some kind of "include X in result" flags

**Comment by kRITZCREEK** [comment]
for a list of identifiers to the type command, we'd presumably also want a list of list of filters so I don't think we gain anything here, as the actual protocol overhead is minimal. I could image a *detailed* flag for the completion command would be the simplest route.

**Comment by nwolverson** [comment]
This might be enabled differently (lazily fill in location) by https://github.com/Microsoft/vscode/pull/10062 (though not sure that works for document verison)

**Comment by nwolverson** [comment]
With psc-ide changes in 0.10 this is now implemented (0.4.0), both go to symbol and show all symbols
