### ISSUE TITLE
Go to/types for operators

### ISSUE THREAD

**Issue by texastoland** [nwolverson/vscode-ide-purescript#27]
I was working late last night without connectivity and had to figure out by associated filename.

**Comment by nwolverson** [comment]
I think this probably wants #25 to do it the Code way

![screen shot 2016-08-02 at 19 02 55](https://cloud.githubusercontent.com/assets/2770891/17339442/caf35cb6-58e3-11e6-8a2b-581cf8aae90a.png)

But can probably open an input window & display the result list

**Comment by texastoland** [comment]
I can wait for #25. I'm totally drinking the Code-Aid 🍷

**Comment by texastoland** [comment]
Is there a technical encumbrance with the popup?

**Comment by nwolverson** [comment]
I think there is an API for an input box, and for a select list, but not a filterable/autocomplete (particularly with async populate).

The 2-step implementation of this should be easy, even a "good first feature".

**Comment by texastoland** [comment]
I meant types on hover?

**Comment by nwolverson** [comment]
Oh. Not sure quite where that's excluded & whether there will be any consequences of allowing it.

**Comment by nwolverson** [comment]
Type hover for operators is now in, goto definition will be available immediately (I think) if psc-ide returns the locations at some point
