### ISSUE TITLE
Assistance for unicode input

### ISSUE THREAD

**Issue by freebroccolo** [nwolverson/vscode-ide-purescript#33]
I have ported the agda input method to vscode and made it available in the [vscode-input-assist](https://github.com/freebroccolo/vscode-input-assist) extension. If I recall correctly, the Atom mode has some sort of latex input for unicode so maybe it would be worth adding this extension to the dependencies here to have feature parity.

If you think it is worth adding the dependency, it would be best to change the `wordPattern` to something like [this](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/extension.ts#L90).

The extended `wordPattern` is needed due to how the vscode completion algorithm works. Without it, some completions like `\<=>n` (⇎) cannot be typed because the completion widget will close as soon as a non-word character is typed after `\`.

**Comment by nwolverson** [comment]
There's no unicode handling in the Atom package (or such dependency), but there exists a latex input package, I only went as far as making sure they work together.

To my mind the best thing here is to do the same - I can change the word pattern here but let you install the extension if you see fit. Maybe mention it in the README. Does that seem reasonable?

**Comment by freebroccolo** [comment]
> To my mind the best thing here is to do the same - I can change the word pattern here but let you install the extension if you see fit. Maybe mention it in the README. Does that seem reasonable?

That sounds reasonable I think.

**Comment by nwolverson** [comment]
Updated README & [language-purescript](https://github.com/nwolverson/vscode-language-purescript) to enable this input.
