### ISSUE TITLE
Allow variable substitution in pscIdeServerExe

### ISSUE THREAD

**Issue by srid** [nwolverson/vscode-ide-purescript#34]
VScode supports [variable substitution](https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution) in certain config variables. Supporting it in the `"purescript.pscIdeServerExe"` config variable would allow me to specify a local node binary relative to project root. Currently this doesn't work as evidenced by the error below:

```
Couldn't find psc-ide-server, check PATH. Looked for: ${workspaceRoot}/node_modules/.bin/psc-ide-server in PATH: [snip]
```

**Comment by nwolverson** [comment]
The linked information is about tasks.json, is there something about the use of this in configuration? I can't see why this wouldn't be a Code feature, not to do with this particular plugin.

**Comment by srid** [comment]
Right, it makes sense to implement this in VScode. There is a feature request tracking this: https://github.com/Microsoft/vscode/issues/2809

**Comment by nwolverson** [comment]
Variable substitution aside, it looks like you're trying to run psc-ide-server from the local npm installation. The `addNpmPath` config should let this be picked up automatically by adding it to your PATH

**Comment by srid** [comment]
> The addNpmPath config should let this be picked up automatically by adding it to your PATH

Not sure what you mean here. Is this something I, as an user, can do? Googling for `addNpmPath` I came across its use in [the Atom plugin](https://github.com/nwolverson/atom-ide-purescript/blob/master/src/IdePurescript/Atom/PscIdeServer.purs#L55-L61).

**Comment by srid** [comment]
Oh nevermind. Reading that source code I understood that this needs to be added to the workspace setting:

```
  "purescript.addNpmPath": true
```
