### ISSUE TITLE
Don't query psc-ide-server with unsaved files

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#37]
Similar to https://github.com/nwolverson/atom-ide-purescript/issues/140. It causes `psc-ide-server` to crash, but really it's unnecessary to query with a file known to not exist.

**Comment by natefaubion** [comment]
I currently have an unsaved buffer open, and every time I tab past it, it crashes psc-ide-server 😬

**Comment by nwolverson** [comment]
Nice! Thanks for reporting.
