### ISSUE TITLE
Autocomplete for text symbols

### ISSUE THREAD

**Issue by splodingsocks** [nwolverson/vscode-ide-purescript#38]
I guess I rely on autocomplete a lot.

I was wondering if we could have this same behavior from the Atom IDE:
https://github.com/nwolverson/atom-ide-purescript/commit/c1f4ec2945fb7b663d729528617045847055d1d7

Because I can't get autocomplete on any of my non-top-level symbols otherwise.
Thanks!

**Comment by nwolverson** [comment]
Not sure if it's possible for multiple completion providers to be active, as far as I recall I don't do anything particular to suppress the plain text suggestions. Happy to be informed.

Ideal solution for me is psc-ide to eventually support local identifiers in more informed way via working on whole AST not top-level info present in externs.

**Comment by Krzysztof-Cieslak** [comment]
VSCode has plain text, fuzzy suggestions system enabled by `editor.wordBasedSuggestions` setting. (Tho, it should be enabled by default)

**Comment by nwolverson** [comment]
Thanks, I'll retest this - my recollection was that those default suggestions were suppressed when results are returned but I'm sure I remember seeing them crop up

**Comment by nwolverson** [comment]
Closing per previous comment.
