### ISSUE TITLE
Import module completion substitutes incorrectly

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#39]
If I start typing `import SlamData.Eff`, I'll get the auto-complete for `SlamData.Effects`, but if I accept, it inserts `SlamData.SlamData.Effects`.

**Comment by nwolverson** [comment]
SlamData, so good they named it twice?

**Comment by nwolverson** [comment]
Just published fix for this, please let me know if it works for you :)

**Comment by natefaubion** [comment]
Thanks! Works great :)
