### ISSUE TITLE
Error: Unrecognised arguments: --json-errors

### ISSUE THREAD

**Issue by dogwith1eye** [nwolverson/vscode-ide-purescript#40]
I'm getting a build error in VS Code when i try to use the pulp build command from the command palette, so i thought i would try the build on the command line.

bash-3.2$ pulp --version
Pulp version 10.0.0
psc version 0.10.5 using /usr/local/bin/psc
bash-3.2$ pulp build --no-psa --json-errors
Error: Unrecognised arguments: --json-errors

I see that psc supports --json-errors

bash-3.2$ psc --help
--json-errors            Print errors to stderr as JSON

But i don't see any support for that with pulp

bash-3.2$ pulp build --help
--no-psa                    Do not attempt to use the psa frontend instead of pic

Ideas?

**Comment by nwolverson** [comment]
For `pulp` since version 10? you need to use a command `pulp build -- --json-errors`, whereas before that version it is  `pulp build --json-errors`.

The default command needs to be updated for newer pulp versions.

**Comment by dogwith1eye** [comment]
Thanks! Figured it was somethings simple!

**Comment by nwolverson** [comment]
Fix (updated default) in 089419c8101735f37cabacd38d4f1bd1cd3f837d
