### ISSUE TITLE
No longer connects to existing psc-ide-server

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#41]
I used to be able to run psc-ide-server in debug mode, and then when I reloaded the window it would connect to the running instance. Now when I reload the window it appears to always kill the existing server, start up a new one, and overwrite the `.psc-ide-port` file. This is making it difficult to debug some issues I'm having.

**Comment by nwolverson** [comment]
That sounds annoying. Not clear on exactly what you're doing, did you at some point kill a running server and start a `--debug` server on that port?

I think the intention was "kill a server if I started it", which this looks kinda like - maybe first starting a server then the editor would help? Or actually switching the port the debug server is running on and putting a new port in that file?

**Comment by natefaubion** [comment]
I think this is an issue on my part then. If I kill the process, and then change the port first before starting the debug server, it will connect correctly. Thanks!

**Comment by nwolverson** [comment]
Certainly it's non obvious, it doesn't just kill the original pid because it's actually sending a quit command over the connection.

Maybe some instructions would help for doing the above, though I think that just logging the communication client-side could be another answer.
