### ISSUE TITLE
Make psc-ide-server optional

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#42]
I tried setting `fastRebuild` to `false` in my default language configuration (opting to only enable it per project), but I don't think this settings does anything anymore. Often times the plugin is too eager about trying to launch a server. For example, just opening the PureScript language settings in a fresh window tries to launch a server (resulting in an error). Sometimes I want to open up or work on random PureScript files, and the launch errors are off-putting.

**Comment by natefaubion** [comment]
I should clarify, I have `fastRebuild` set to `false` in both user settings and language settings.

**Comment by nwolverson** [comment]
Certainly, `fastRebuild` wouldn't be what triggers launching a server, it is done on opening a file to support autocomplete, tooltips, etc.

Are you basically looking for a configuration option to disable the extension which you can apply per workspace? It seems this should be a vscode feature but isn't, so I'd be happy to temporarily include

Or are you thinking to make launching a server non-automatic? Again fine by me as long as it's not the default, as it means many things will just "not work". 

I'll have a play around and investigate some individual points you raise

**Comment by natefaubion** [comment]
> Or are you thinking to make launching a server non-automatic? Again fine by me as long as it's not the default, as it means many things will just "not work".

Yeah I think this is all I'm really requesting.

**Comment by nwolverson** [comment]
Done! 4c6ed62498f5b2961c8d21dbbd7f8ba0a45990e2
