### ISSUE TITLE
Search on Pursuit

### ISSUE THREAD

**Issue by jgoux** [nwolverson/vscode-ide-purescript#45]
Hello,

I often go to Pursuit in order to search a function by a type definition.

Would it be possible to integrate a command to search directly on Pursuit within VS Code ?

**Comment by nwolverson** [comment]
Should be, this feature is in the atom version, I think code now provides the appropriate UI hooks

**Comment by nwolverson** [comment]
Pursuit search added https://github.com/nwolverson/vscode-ide-purescript/releases/tag/v0.9.0
