### ISSUE TITLE
Request Opinion: VS Code and Atom

### ISSUE THREAD

**Issue by RAbraham** [nwolverson/vscode-ide-purescript#49]
Hi Nicholas,

I'm researching IDEs and I was wondering if you could share your experiences writing plugins for both Atom and VS Code. Do you prefer one over the other and if you have to support just one IDE, which one would you prefer?

Thanks,
Rajiv

**Comment by nwolverson** [comment]
Code by far, the API support provided is excellent and has expanded pretty rapidly, if something is possible then it's probably easy to do and works well. The one benefit of Atom is you can do *anything*, build your own custom UI to do precisely what you want, however while there are common APIs provided for IDE tasks (e.g. autocomplete) many are missing, and various language plugins inventing the wheel.

**Comment by RAbraham** [comment]
That is valuable feedback. Downloaded VS Code to try it out :). Thanks!
