### ISSUE TITLE
Can't find psc-ide-server in PATH

### ISSUE THREAD

**Issue by cjhoward92** [nwolverson/vscode-ide-purescript#50]
I just get this error when I open vscode

`Couldn't find psc-ide-server, check PATH. Looked for: psc-ide-server in PATH:`

How do I add `psc-ide-server` to the path? I don't even know where it is supposed to be installed by the purescript compiler.

I downloaded purescript and pulp today from npm so I have no idea why I get this error. I can't get the deprecated [psc-ide](https://github.com/kRITZCREEK/psc-ide) to build in stack either.

Any suggestions? What other info do you need?

**Comment by nwolverson** [comment]
If you are using purescript 0.11.x you need to enable the "use combined executable" option. The command used is now `purs`, included with the compiler, `psc-ide-server` is the old version for 0.10.x and below (still used by default).

**Comment by cjhoward92** [comment]
Right. Thank you! Works like a charm!
