### ISSUE TITLE
Adding imports via Ctrl+Space eats newlines on Windows

### ISSUE THREAD

**Issue by cebaa** [nwolverson/vscode-ide-purescript#52]
Here is what I have:

```
module A where
-- empty line
import Prelude
-- empty line
f :: String -> Maybe String
```

Go after Maybe, press Ctrl+Space. This imports Data.Maybe and I want this:

```
module A where
-- empty line
import Prelude
import Data.Maybe (Maybe)
-- empty line
f :: String -> Maybe String
```

But I get this:

```
module A where
-- empty line
import Prelude
import Data.Maybe (Maybe)
f :: String -> Maybe String
```

It eats declarations when no empty lines exist. Works on Linux.

Pulp version 11.0.0
purs version 0.11.3

**Comment by nwolverson** [comment]
I like that you're more protective of blank lines than your declarations!

I can reproduce this, will take a look

**Comment by nwolverson** [comment]
See the linked issue, looks like a psc-ide issue if your file is CRLF. As a workaround you may wish to edit in LF (it's an easy toggle in vscode at the bottom right).

**Comment by cebaa** [comment]
Thanks @nwolverson!

**Comment by cebaa** [comment]
One small note - looks like purescript 0.11.4 fixes this bug through https://github.com/purescript/purescript/issues/2833. So this works fine now, except that when you import things the cursor is one line above than where it should be.

I.e. (_ denotes current cursor position

```
-- blah comment
hello = fromJust_
```

After Ctrl+Space (to auto import `fromJust`) this becomes

```
-- blah comment _
hello = fromJust
```

**Comment by nwolverson** [comment]
Need to retest this with latest compiler changes around the newline handling here, and extension updates.

**Comment by nwolverson** [comment]
Looks to me like the cursor position being wrong is no longer the case - tested on windows with 0.11.5 / plugin 0.11.1.
