### ISSUE TITLE
Feature Request: Run Code(ctrl+alt+N)

### ISSUE THREAD

**Issue by RAbraham** [nwolverson/vscode-ide-purescript#55]
Hi,
One feature that I use frequently is running the `main` command within the IDE. An example of this is shown [here(after 0:38)](https://egghead.io/lessons/model-problems-using-algebraic-data-types-adts).

I got something similar hacky using a task runner running `pulp run`. But I see that if one right clicks on the `purs` file, one sees the option `Run Code`. When I click on that, I get the `info` message `Code language not supported or defined.`

I was wondering what you thought of binding that to a behaviour which runs the `main` command in the file where it was executed. Would this fall under the `vscode-ide-purescript` project or is it external to it?

**Comment by nwolverson** [comment]
Looks like you're using the [Code Runner](https://github.com/formulahendry/vscode-code-runner) extension, I think that is where "run code" comes from. Configuring that would be an option.

I'd note that it seems to be targeted at running particular files or selections, not sure if that makes sense or not. I think that a task-runner would be the usual VSCode way to do this? You can set them to run in the terminal I think too https://github.com/Microsoft/vscode/issues/19057

**Comment by RAbraham** [comment]
my bad, I didn't realize it was a `Code Runner` feature. Thanks!
