### ISSUE TITLE
Add import occasionally wipes out entire document

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#58]
Not figured out what the conditions are yet. Occasionally I hit tab to complete and add import, and the entire document other than the module definition is wiped out. Undo brings it back.

**Comment by DevNebulae** [comment]
It seems to only happen whenever the import already exists.

**Comment by nwolverson** [comment]
Thanks for the input; that doesn't seem to be entirely it, I think I see it just when importing a data constructor which is already imported with the `(..)` form, e.g. Importing `Just` fails for:

```purescript
import Data.Maybe(..)
```

But not for 

```purescript
import Data.Maybe(Just,Nothing)
```

or no existing import.

Looking into why now

**Comment by DevNebulae** [comment]
Can confirm that it will not happen with functions and that it primarily happens with data constructors.

**Comment by nwolverson** [comment]
Well this is my stupid fault, just published a fix.
