### ISSUE TITLE
Code breaks on imports claiming it was not found

### ISSUE THREAD

**Issue by DevNebulae** [nwolverson/vscode-ide-purescript#59]
Whenever I have imports, the IDE breaks on import statements claiming they were not found with the following error message:

```
Module Control.Monad.State was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.
```

Is there a fix for this or is it a bug?

Purescript version: 0.11.4
Pulp version: 11.0.0

**Comment by DevNebulae** [comment]
I seem to have found a solution which makes the errors go away and that is that I changed the `purescript.addNpmPath` from `false` to `true`. Is there an explanation for this?

**Comment by nwolverson** [comment]
It sounds like you have a locally installed version of purescript, if you are building with a local installation, then you should also use that installation for the IDE server (which that flag enables). Otherwise you may have a version mismatch.

**Comment by DevNebulae** [comment]
I ran `sudo npm i -g purescript pulp` and then I got these errors. Is the IDE meant to be used in another way?

**Comment by nwolverson** [comment]
Then I'm surprised this would have any effect, are you sure you have nothing in `node_modules/purescript` or `node_modules/pulp` in the project? Otherwise I suspect that maybe this change was unrelated to things starting to work - if you have not built your solution prior to loading, the IDE server will be unable to find any modules. In that case (among other things) "restart psc-ide-server" menu option would probably have kicked things into working after doing a full build.

**Comment by DevNebulae** [comment]
There is no such folder in my project and the error was happening even after building the project, resetting VS Code and rebuilding the project. Before, it wouldn't work even before consulting all important steps.

**Comment by nwolverson** [comment]
What does resetting VS Code mean? How are you building the project? Are you seeing the errors after using the build command ("PureScript: Build") or saving a single file?

I'm afraid there isn't enough information here to reproduce the issue.

**Comment by DevNebulae** [comment]
With resetting VS Code I meant shutting it down and starting it again. I produced some result with the following steps:

* Remove  all PureScript related folders and settings (like `.psc-ide-port` and `.pulp-cache`);
* Start VS Code;
* Save file;
* Should error on imports about missing files.

However, this is normal since the command the plugin relies on (`purs ide server`) would give the same error. I was getting it constantly while the crucial files and folders were present. I figure what happened was that I just upgraded my PureScript version and that it got stuck in its old state.

**Comment by nwolverson** [comment]
So is this issue resolved? Any further problem here?

**Comment by DevNebulae** [comment]
One thing I noticed, and this is probably where my issue came from, is when I add a new module, compile it and then re-save the file (type a space and hit Ctrl + S), the error will still be there about the missing module. It will go away if I close VSCode and open it again. I think it needs to watch for changes in the configured output folder and when it does, do some re-check if the module is now there.

**Comment by txsmith** [comment]
I have the same issue, but setting `purescript.addNpmPath` to `true` does not seem to help in my case. @DevNebulae were you able to resolve this?

**Comment by DevNebulae** [comment]
@txsmith If you're talking about my first issue: yes, but that was just with sheer luck. I have no clue how I resolved that.

**Comment by nwolverson** [comment]
Running the full "build" command ('PureScript: Run Build' from the command palette) should fix missing modules errors. If you run build with no errors, and saving the file still gives missing modules, I'd love to know enough to reproduce.

I've tried without building first and building with the wrong version, in each case running a build fixes it (I'm going to add this as a suggested fix action).

**Comment by DevNebulae** [comment]
@nwolverson It indeed seems to work when you do that. It would be cool if it would partially build what you just saved and resolve the issue from there. Definitely infinitely more easy than restarting VSCode all over again.

**Comment by txsmith** [comment]
Yes that works for me too

**Comment by nwolverson** [comment]
This seems to be just the way rebuild works in psc IDE server. Added rebuild suggestion to the UnknownModule error, please reopen if there's a futher issue I'm missing

**Comment by foxdonut** [comment]
Just in case someone comes by here with this problem. I had the same issue and the solution was to make sure to open the project folder in VS code, not a parent folder.

**Comment by remisa-yousefvand** [comment]
For me running the command `bower update` before `pulp build` solved the problem.

**Comment by fes300** [comment]
@nwolverson I have the same problem on a public repo if you want to reproduce this https://github.com/fes300/fes300.github.io.

**Comment by waynevanson** [comment]
I checked the output tab of `IDE Purescript` from the command palette and found this:

```
[Info  - 6:57:56 AM] [Info] cachedb was changed from: Nothing, to: Just 2021-01-21 06:45:00.426275133 UTC @(main:Command.Ide app/Command/Ide.hs:205:25)
[Error] Version mismatch for the externs at: /home/wayne/Documents/code/purescript/purescript-accounting/output/Data.Bifunctor/externs.cbor Expected: 0.13.8 Found: 0.14.0
```

Deleting the `output` and `.spago` folders resolved my version of the issue.
