### ISSUE TITLE
Undo after adding import prevents import being re-added

### ISSUE THREAD

**Issue by DevNebulae** [nwolverson/vscode-ide-purescript#60]
Here's how I got the auto-import feature to break:

* Create a file with the contents at the bottom of this message;
* Hit tab when typing the `/` character;
* Press CTRL + Z until the import is gone;
* Hit tab when typing the `/` character;

Result:

Auto-import feature now is not working and it will just skip over the character. Also, a small annoyance I found is that I now can't auto-import definitions when hitting enter, it either doesn't import the module or it just goes to the next line.

File:

    module Application.State where
    
    rpmPerMillisecond :: Number -> Number
    rpmPerMillisecond rpm = rpm / 60 / 1000

**Comment by nwolverson** [comment]
Did you save the file after the first import was removed? That should make it eligible for import again.

That's one issue I'm aware of, intending to fix now that psc-ide has lenient import parsing

**Comment by DevNebulae** [comment]
I didn't, but that indeed is the issue. Is the not behavior with the enter key intended by the way?

**Comment by DevNebulae** [comment]
To add to my last comment, it seems to work after I saved the file. So hitting enter after you have unsaved changes and removed an import seems to break the behavior with the enter key.

**Comment by nwolverson** [comment]
Re-adding import should be fixed by 0.10.0
