### ISSUE TITLE
psc-ide-based autocompletion hangs the UI while typing

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#61]
This started happening to me recently in SlamData, on certain autocompletions it will hang the UI when I type as long as I have an ide server running. If I turn off the server, I don't have any issues, but then I can't do quick compiles. Maybe an option to turn off psc-ide-based autocompletions would do well.

**Comment by natefaubion** [comment]
I fixed this temporarily by switching `autoCompleteAllModules` to `false`.

**Comment by nwolverson** [comment]
With the latest version & .11.5 compiler there's a completion limit (configured as `purescript.autocompleteLimit`) enforced on the server side, can you see if that helps in your scenario? Maybe a little complicated by the move to a language server backend, so I'd also be on the lookout for other slowness that doesn't hang the UI.

**Comment by nwolverson** [comment]
@natefaubion did you get a chance to see if the limit resolves the issue? Assuming you're on 0.11.5 yet

**Comment by nwolverson** [comment]
Closing this as I believe the autocomplete limit should have resolved any issue, @natefaubion feel free to reopen if the issue can still be reproduced after those changes.
