### ISSUE TITLE
Add support for configurable source path

### ISSUE THREAD

**Issue by istonikula** [nwolverson/vscode-ide-purescript#63]
Currently package path can be customized via packagePath config variable but source path is not customizable.

`"src/**/*.purs", packagePath <> "/**/*.purs"`

With the default values (where packagePath is bower_components) the IDE's support functions like 'Go to definition' and 'Go to Symbol in File' work for libs, but not for my project's source code where purs files are not directly under src folder. If I set packagePath to point to my sources, then I get aforementioned IDE features to work with my code, but lose them for the libs.

I would be nice to be able to customize the source path in a similar way that is already supported for package path.

**Comment by nwolverson** [comment]
Interim workaround: Set packagePath to `{bower_components,my_src}`, I think it's only used for this glob
