### ISSUE TITLE
Add dependency to aliased import 

### ISSUE THREAD

**Issue by DevNebulae** [nwolverson/vscode-ide-purescript#72]
It would be nice if the package covered the following use case. When having the following import

    import DOM.Node.Types (Element) as DOM

And I type the following

    document :: DOM.Document

I expect the `Document` import to be added to the aforementioned import, however it creates a new import. It would be nice if the package added that import to the aliased import.

**Comment by nwolverson** [comment]
Yes, that's a stupid bug for sure, it certainly shouldn't do that.

Probably also want to look at the emacs plugin which does some helpful stuff around qualified imports on completion.

**Comment by nwolverson** [comment]
The bug itself was fixed, leaving the issue open as enhancement to look into the other assistive case (where the qualifier is not already imported)

**Comment by nwolverson** [comment]
The enhancement should now also be present with https://github.com/nwolverson/purescript-language-server/commit/f6fc0af2f8c88ef2ca630a1813730aea558b3512
