### ISSUE TITLE
Error when building extension

### ISSUE THREAD

**Issue by hakonrossebo** [nwolverson/vscode-ide-purescript#74]
Not sure if I'm doing this right. When I try to build the project, I'm getting this error when running npm run build:

<details>
src/LanguageServer/Handlers.ts(18,80): error TS2345: Argument of type '(handler: NotificationHandler<DidChangeConfigurationParams>) => void' is not assignable to parameter of type '(handler: RequestHandler<DidChangeConfigurationParams, void, void>) => void'.
  Types of parameters 'handler' and 'handler' are incompatible.
src/LanguageServer/Handlers.ts(26,79): error TS2345: Argument of type '(handler: NotificationHandler<DidChangeWatchedFilesParams>) => void' is not assignable to parameter of type '(handler: RequestHandler<DidChangeWatchedFilesParams, void, void>) => void'.
  Types of parameters 'handler' and 'handler' are incompatible.
src/LanguageServer/Handlers.ts(28,62): error TS2345: Argument of type '(handler: NotificationHandler0) => void' is not assignable to parameter of type '(handler: RequestHandler<{}, void, void>) => void'.
  Types of parameters 'handler' and 'handler' are incompatible.
src/LanguageServer/Handlers.ts(30,66): error TS2345: Argument of type '(handler: RequestHandler0<void, void>) => void' is not assignable to parameter of type '(handler: RequestHandler<CancellationToken, void, void>) => void'.
  Types of parameters 'handler' and 'handler' are incompatible.

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "tsc:lsp"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ide-purescript@0.11.0 tsc:lsp: `tsc -p src/LanguageServer/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ide-purescript@0.11.0 tsc:lsp script 'tsc -p src/LanguageServer/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ide-purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/LanguageServer/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ide-purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ide-purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hakon/.npm/_logs/2017-06-28T19_21_35_274Z-debug.log
ERROR: "tsc:lsp" exited with 2.

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ide-purescript@0.11.0 build: `npm-run-all tsc:* psc:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ide-purescript@0.11.0 build script 'npm-run-all tsc:* psc:*'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ide-purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all tsc:* psc:*
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ide-purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ide-purescript
npm ERR! There is likely additional logging output above.
</details>

Using the latest versions of purescript, pulp, bower. Have run npm install.

Also, when developing for vscode-elm, i can use F5 to run launch tasks for debugging the extension - is there any configuration for this?

**Comment by nwolverson** [comment]
Looks at a glance like some version isn't locked down sufficiently. Was building ok on the CI https://travis-ci.org/nwolverson/vscode-ide-purescript/builds/241761014

I'm running `npm run build` from a launch task; I guess I can add the `.vscode` to the repo

**Comment by nwolverson** [comment]
I think this should be fixed, the latest typescript picked up that I had some bad callback types & the version was not sufficiently constrained

**Comment by hakonrossebo** [comment]
Thanks. Got a step further. Now I get this error:

<details>
> ide-purescript@0.11.0 tsc:ffi /home/hakon/source/repos/vscode-ide-purescript
> tsc -p src/VSCode/

node_modules/vscode-languageclient/lib/client.d.ts(4,712): error TS2307: Cannot find module 'vscode'.
node_modules/vscode-languageclient/lib/codeConverter.d.ts(1,23): error TS2307: Cannot find module 'vscode'.
node_modules/vscode-languageclient/lib/main.d.ts(5,28): error TS2307: Cannot find module 'vscode'.
node_modules/vscode-languageclient/lib/protocolCompletionItem.d.ts(1,23): error TS2307: Cannot find module 'vscode'.
node_modules/vscode-languageclient/lib/protocolConverter.d.ts(1,23): error TS2307: Cannot find module 'vscode'.
src/VSCode/Command.ts(1,25): error TS2307: Cannot find module 'vscode'.
src/VSCode/Command.ts(4,47): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.
src/VSCode/Command.ts(11,62): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/VSCode/Command.ts(14,9): error TS7006: Parameter 'err' implicitly has an 'any' type.
src/VSCode/Diagnostic.ts(1,55): error TS2307: Cannot find module 'vscode'.
src/VSCode/Input.ts(1,56): error TS2307: Cannot find module 'vscode'.
src/VSCode/Input.ts(4,39): error TS7006: Parameter 'x' implicitly has an 'any' type.
src/VSCode/Location.ts(3,41): error TS2307: Cannot find module 'vscode'.
src/VSCode/Notifications.ts(3,25): error TS2307: Cannot find module 'vscode'.
src/VSCode/Position.ts(3,26): error TS2307: Cannot find module 'vscode'.
src/VSCode/TextDocument.ts(1,25): error TS2307: Cannot find module 'vscode'.
src/VSCode/TextDocument.ts(2,47): error TS2307: Cannot find module 'vscode'.
src/VSCode/TextDocument.ts(5,54): error TS7006: Parameter 'doc' implicitly has an 'any' type.
src/VSCode/TextEditor.ts(1,35): error TS2307: Cannot find module 'vscode'.
src/VSCode/TextEditor.ts(4,13): error TS7006: Parameter 'builder' implicitly has an 'any' type.
src/VSCode/TextEditor.ts(5,15): error TS7006: Parameter 's' implicitly has an 'any' type.
src/VSCode/TextEditor.ts(28,13): error TS7006: Parameter 'builder' implicitly has an 'any' type.
src/VSCode/TextEditor.ts(29,15): error TS7006: Parameter 's' implicitly has an 'any' type.
src/VSCode/TextEditor.ts(34,13): error TS7006: Parameter 'builder' implicitly has an 'any' type.
src/VSCode/TextEditor.ts(35,15): error TS7006: Parameter 's' implicitly has an 'any' type.
src/VSCode/Window.ts(1,53): error TS2307: Cannot find module 'vscode'.
src/VSCode/Workspace.ts(1,51): error TS2307: Cannot find module 'vscode'.

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "tsc:ffi"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ide-purescript@0.11.0 tsc:ffi: `tsc -p src/VSCode/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ide-purescript@0.11.0 tsc:ffi script 'tsc -p src/VSCode/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ide-purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/VSCode/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ide-purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ide-purescript
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hakon/.npm/_logs/2017-06-29T06_21_43_182Z-debug.log
ERROR: "tsc:ffi" exited with 2.

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ide-purescript@0.11.0 build: `npm-run-all tsc:* psc:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ide-purescript@0.11.0 build script 'npm-run-all tsc:* psc:*'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ide-purescript package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all tsc:* psc:*
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ide-purescript
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ide-purescript
npm ERR! There is likely additional logging output above.
</details>

**Comment by nwolverson** [comment]
That's odd, it's definitely building on the CI as of yesterday. Maybe have a look at this and compare to your own build: https://travis-ci.org/nwolverson/vscode-ide-purescript/builds/248143477?utm_source=github_status&utm_medium=notification

Maybe check what version of `vscode` node module is installed, possibly try nuking and reinstalling node modules?

**Comment by hakonrossebo** [comment]
Solved. Had Npm 4.2.0 installed and somehow it was not running the postinstall script. Build worked fine when running postinstall manually. Updated to latest Npm 5.0.4, nuked node modules and npm install, npm run build and everything worked :)

**Comment by nwolverson** [comment]
Great. Odd that it also works with npm3 on the CI server.
