### ISSUE TITLE
Invoking the build doesn't change the status icon anymore

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#76]
This was a nice touch that no longer works.

**Comment by nwolverson** [comment]
This the full actual "build" command rather than rebuild on save?

Should be possible to hook this up with language server events. There's also a progress indicator thing that could be used but not sure if it's too obtrusive for a build, not tried it.

**Comment by natefaubion** [comment]
Brilliant. You have no idea how happy this little icon makes me. 👶
