### ISSUE TITLE
Debug logs always come up if there's no ide-server running

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#77]
<img width="856" alt="screen shot 2017-07-03 at 10 16 29 pm" src="https://user-images.githubusercontent.com/144058/27815964-47caedec-603d-11e7-8fa2-296eae2787ee.png">

Can't dismiss it. If I do it just comes back when I start typing.

**Comment by natefaubion** [comment]
Actually this happens very frequently, even when the serer is running. For example, if I autocomplete something that has already imported, it brings up the log with `[Error] Failed to import`. Do you know if this can be turned off? I don't need to see the log on every action.

**Comment by nwolverson** [comment]
I don't recall this happening, definitely not something intentional - IMO the log should just be present in the background if you want to look for it...
