### ISSUE TITLE
Errors sometimes hang around in the problem list after a full build

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#81]
A full build should replace the errors in the problem list. Right now, sometimes errors can hang around after a full build if it's clean.

**Comment by nwolverson** [comment]
Think this is duplicate of #69, which is a case of I've seen the problem and not fixed it yet. This is when a file which previously had errors, after a full build has none?

**Comment by nwolverson** [comment]
Fixed in f4bd218dc13f2d261e9235df98bb2d68882ae5a8 / 0.11.5
