### ISSUE TITLE
Issues with latest VSCode?

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#82]
Since the latest vscode release, I can't initiate builds or start psc-ide server.

<img width="440" alt="screen shot 2017-08-02 at 3 11 37 pm" src="https://user-images.githubusercontent.com/144058/28897301-ea2b6c9c-7794-11e7-957f-d3766dd226e5.png">

All the main commands result in an error like this.

**Comment by nwolverson** [comment]
Please clarify version, is this 1.14.1?

Can you check the "IDE PureScript" output pane

**Comment by nwolverson** [comment]
Actually release notes list 1.14.1 but I'm on 1.14.2 and PureScript 0.11.6, everything working as usual. Hopefully you will find something in the output pane, the server startup info may be helpful, also there should be failure text if commands are failing.

**Comment by natefaubion** [comment]
```
Error: Cannot find module '/Users/nathan/.vscode/extensions/nwolverson.ide-purescript-0.11.4/language-server/cli.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Interesting. Maybe I should just try reinstalling the extension?

**Comment by natefaubion** [comment]
I tried reinstalling the extension, and I'm back in business.

**Comment by nwolverson** [comment]
OK, little worrying but hopefully just some installation went wrong :|

If anybody does spot this again do reopen
