### ISSUE TITLE
Rogue psc-ide-server

### ISSUE THREAD

**Issue by texastoland** [nwolverson/vscode-ide-purescript#9]
…when I open a new project with <kbd>Cmd+O</kbd> (consequently closing the active one).

**Comment by nwolverson** [comment]
Thanks for opening the issue. I think it used to be the case that the psc-ide-server was never closed, and I **think** I fixed that in some case, so hopefully this isn't too hard to fix.

**Comment by nwolverson** [comment]
Actually now I see the code, it is just sending `SIGKILL` which will fail, I must have been thinking of atom.

**Comment by texastoland** [comment]
I'd love to tackle it in about a month if you don't get to it first. Is there an API to discover all the top level identifiers yet? I assume it could be pulled from JSON worst case.

**Comment by nwolverson** [comment]
Think you commented on the wrong issue. What would you want a list of all identifiers for? Generally psc-ide provides info on a per-request basis, eg for a token that may or may not be an identifier of a  top-level definition.

**Comment by texastoland** [comment]
Sorry I was just thinking about features I miss using PS. Both VS Code and Atom have a symbols view and navigatioin. Other features I miss I think are related: <kbd>Cmd+click</kbd> navigation between symbols, renaming, and a more configurable build.

**Comment by nwolverson** [comment]
Added #10 for navigation; what do you mean by renaming? Don't think we have the basis to handle that properly. And what specifically about the configurable build? I think the full build command line is configurable. Would be good to open an issue to track.

**Comment by texastoland** [comment]
In VS Code you can safely rename all usages for a thing. I assume you're right we need something fancier from psc-ide for that. I'll open an issue for build later!
