### ISSUE TITLE
Identifier module no longer shown in Intellisense

### ISSUE THREAD

**Issue by Houndolon** [nwolverson/vscode-ide-purescript#93]
E.g. for functions Intellisense showed the type signature and the containing module, now it only shows the type signature.
![image](https://user-images.githubusercontent.com/9405688/34586797-cee4c970-f1a5-11e7-996e-600df5b17314.png)

**Comment by nwolverson** [comment]
Please confirm the version you have installed, this should be fixed already but may require a bump to the required language server version before it's picked up.

**Comment by Houndolon** [comment]
Back again in 0.13.0.
