### ISSUE TITLE
Problems with purescript projects as subfolders…

### ISSUE THREAD

**Issue by hedefalk** [nwolverson/vscode-ide-purescript#95]
I moved around a few projects and noticed that I couldn't have purescript projects in subdirectories because the language server was started on the root and then I just got 'Prelude not defined' errors.

Couldn't one traverse upwards from the purs file or something to find project instead of using vscode folder root? Or let there be some kind of settings…?

**Comment by nwolverson** [comment]
In this case I think you should use the multiple folder workspace functionality of vscode to open these projects at the root level (at least for now). You can then configure these projects individually in vscode if required too.

The multi-workspace/root folder behaviour of this extension is modelled on [vscode-extension-samples/lsp-multi-server-sample](https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-server-sample/client/src/extension.ts), but what you describe is a bit closer to what I used to do in the Atom plugin. I guess this could be modified to traverse upwards until *either* project found or workspace root hit; and some more subtlety elsewhere around folder changes etc.

**Comment by hedefalk** [comment]
@nwolverson Thx!

Yes, I guess the workspace functionality is what I need to use. I haven't really gotten used to it yet because it seems to be overlapping / conflicting a bit in flow with the project manager plugin I'm used to (also coming from Atom). I basically don't want to have to use files to open workspaces/projects but just shortcuts in-app. But I guess that's a different discussion :)

By the way, I did something similar also with traversing down for the Scala Ensime plugin in Atom. https://github.com/ensime/ensime-atom/
