### ISSUE TITLE
purs ide feature don't work on new files

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#97]
If I open a fresh tab in a workspace and change the language mode to PureScript, purs ide features are not available until I save the file. I could have sworn this used to work fine previously. Am I imagining that?

**Comment by nwolverson** [comment]
In a workspace with existing purs project, ie purs ide is already running, but the new file has no file path yet?

This could be a consequence of multiple-root workspace support, files must be under some root folder  to know what language/ide server to talk to, we don't really have an "orphan" context. I suppose we could initially assume the first root folder.

**Comment by natefaubion** [comment]
> In a workspace with existing purs project, ie purs ide is already running, but the new file has no file path yet?

Correct, everything works otherwise for the workspace, just not the new file.

**Comment by nwolverson** [comment]
I believe this is this case https://github.com/nwolverson/vscode-ide-purescript/blob/master/src/extension.ts#L44

**Comment by natefaubion** [comment]
Is there a way to detect when the file type changes, rather than on file open?

**Comment by nwolverson** [comment]
Maybe `onDidChangeTextDocument`, regardless the `getWorkspaceFolder` obviously won't work
