### ISSUE TITLE
New project experience

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/vscode-ide-purescript#98]
Per https://github.com/nwolverson/purescript-language-server/issues/17 - anything that vscode plugin itself can do or is it all in LS

**Comment by natefaubion** [comment]
I think we should try to detect a build, and if there isn't one, throw up a confirmation to run one according to the workspace settings.

**Comment by nwolverson** [comment]
Doing this now https://github.com/nwolverson/purescript-language-server/issues/17
